# nullable enable

// <auto-generated>
//   This file was generated by Toarnbeike.Unions.StaticGenerator.
//   Generator: MapPartialExtensionsGenerator (v. 1.0.0)
//   Created: 2025-12-19 08:58:01Z
//   This is an auto-generated file. Do not modify.
// </auto-generated>

namespace Toarnbeike.Unions.Extensions;

/// <summary>
/// Map: extension methods to map union values, modifying the inner value, but keeping the types equal (endomorphic).
/// </summary>
/// <remarks>
/// This files deals with partial Map: transforms a single member of the union if the union is in that specific state.
/// For modifying all values at once (full map), see the other part of this partial class.
/// </summary>
public static partial class MapExtensions
{
    #region Map Extensions for Union<T1, T2>

    extension<T1, T2>(Union<T1, T2> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2>(Task<Union<T1, T2>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion

    #region Map Extensions for Union<T1, T2, T3>

    extension<T1, T2, T3>(Union<T1, T2, T3> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3> MapT3(Func<T3, T3> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3>.FromT3(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3>.FromT3(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2, T3>(Task<Union<T1, T2, T3>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT3(Func<T3, T3> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT3(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT3Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion

    #region Map Extensions for Union<T1, T2, T3, T4>

    extension<T1, T2, T3, T4>(Union<T1, T2, T3, T4> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4> MapT3(Func<T3, T3> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4>.FromT3(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4> MapT4(Func<T4, T4> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4>.FromT4(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4>.FromT3(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4>.FromT4(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2, T3, T4>(Task<Union<T1, T2, T3, T4>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT3(Func<T3, T3> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT3(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT4(Func<T4, T4> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT4(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT3Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT4Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion

    #region Map Extensions for Union<T1, T2, T3, T4, T5>

    extension<T1, T2, T3, T4, T5>(Union<T1, T2, T3, T4, T5> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5> MapT3(Func<T3, T3> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT3(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5> MapT4(Func<T4, T4> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT4(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5> MapT5(Func<T5, T5> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT5(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT3(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT4(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5>.FromT5(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2, T3, T4, T5>(Task<Union<T1, T2, T3, T4, T5>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT3(Func<T3, T3> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT3(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT4(Func<T4, T4> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT4(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT5(Func<T5, T5> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT5(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT3Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT4Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT5Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion

    #region Map Extensions for Union<T1, T2, T3, T4, T5, T6>

    extension<T1, T2, T3, T4, T5, T6>(Union<T1, T2, T3, T4, T5, T6> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6> MapT3(Func<T3, T3> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT3(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6> MapT4(Func<T4, T4> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT4(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6> MapT5(Func<T5, T5> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT5(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T6 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6> MapT6(Func<T6, T6> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT6(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT6(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT3(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT4(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT5(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T6 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT6Async(Func<T6, Task<T6>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT6(out var value)
                ? Union<T1, T2, T3, T4, T5, T6>.FromT6(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2, T3, T4, T5, T6>(Task<Union<T1, T2, T3, T4, T5, T6>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT3(Func<T3, T3> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT3(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT4(Func<T4, T4> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT4(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT5(Func<T5, T5> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT5(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT6(Func<T6, T6> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT6(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT3Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT4Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT5Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6>> MapT6Async(Func<T6, Task<T6>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT6Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion

    #region Map Extensions for Union<T1, T2, T3, T4, T5, T6, T7>

    extension<T1, T2, T3, T4, T5, T6, T7>(Union<T1, T2, T3, T4, T5, T6, T7> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT3(Func<T3, T3> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT3(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT4(Func<T4, T4> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT4(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT5(Func<T5, T5> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT5(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T6 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT6(Func<T6, T6> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT6(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT6(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T7 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7> MapT7(Func<T7, T7> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT7(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT7(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT3(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT4(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT5(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T6 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT6Async(Func<T6, Task<T6>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT6(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT6(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T7 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT7Async(Func<T7, Task<T7>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT7(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7>.FromT7(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2, T3, T4, T5, T6, T7>(Task<Union<T1, T2, T3, T4, T5, T6, T7>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT3(Func<T3, T3> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT3(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT4(Func<T4, T4> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT4(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT5(Func<T5, T5> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT5(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT6(Func<T6, T6> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT6(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT7(Func<T7, T7> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT7(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT3Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT4Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT5Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT6Async(Func<T6, Task<T6>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT6Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> MapT7Async(Func<T7, Task<T7>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT7Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion

    #region Map Extensions for Union<T1, T2, T3, T4, T5, T6, T7, T8>

    extension<T1, T2, T3, T4, T5, T6, T7, T8>(Union<T1, T2, T3, T4, T5, T6, T7, T8> union)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT1(Func<T1, T1> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT1(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT2(Func<T2, T2> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT2(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT3(Func<T3, T3> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT3(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT4(Func<T4, T4> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT4(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT5(Func<T5, T5> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT5(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T6 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT6(Func<T6, T6> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT6(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT6(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T7 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT7(Func<T7, T7> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT7(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT7(map(value))
                : union;
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the union if it is in the T8 state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public Union<T1, T2, T3, T4, T5, T6, T7, T8> MapT8(Func<T8, T8> map)
       {
           ArgumentNullException.ThrowIfNull(map);

            return union.TryGetT8(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT8(map(value))
                : union;
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T1 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT1(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT1(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T2 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT2(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT2(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T3 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT3(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT3(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T4 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT4(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT4(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T5 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT5(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT5(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T6 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT6Async(Func<T6, Task<T6>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT6(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT6(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T7 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT7Async(Func<T7, Task<T7>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT7(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT7(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           

       /// <summary>
       /// Apply an async mapping function to the value stored in the union if it is in the T8 state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT8Async(Func<T8, Task<T8>> mapAsync)
       {
           ArgumentNullException.ThrowIfNull(mapAsync);

            return union.TryGetT8(out var value)
                ? Union<T1, T2, T3, T4, T5, T6, T7, T8>.FromT8(await mapAsync(value).ConfigureAwait(false))
                : union;
       }                           
    }
    
    extension<T1, T2, T3, T4, T5, T6, T7, T8>(Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> unionTask)
    {

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT1(Func<T1, T1> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT1(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT2(Func<T2, T2> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT2(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT3(Func<T3, T3> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT3(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT4(Func<T4, T4> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT4(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT5(Func<T5, T5> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT5(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT6(Func<T6, T6> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT6(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT7(Func<T7, T7> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT7(map);
       }

       /// <summary>
       /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="map">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT8(Func<T8, T8> map)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.MapT8(map);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT1Async(Func<T1, Task<T1>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT1Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT2Async(Func<T2, Task<T2>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT2Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT3Async(Func<T3, Task<T3>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT3Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT4Async(Func<T4, Task<T4>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT4Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT5Async(Func<T5, Task<T5>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT5Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT6Async(Func<T6, Task<T6>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT6Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT7Async(Func<T7, Task<T7>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT7Async(mapAsync).ConfigureAwait(false);
       }

       /// <summary>
       /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
       /// </summary>
       /// <param name="mapAsync">The mapping function to apply.</param>
       public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> MapT8Async(Func<T8, Task<T8>> mapAsync)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.MapT8Async(mapAsync).ConfigureAwait(false);
       }
    }

    #endregion
}