# nullable enable

// <auto-generated>
//   This file was generated by Toarnbeike.Unions.StaticGenerator.
//   Generator: ProjectFullExtensionsGenerator (v. 1.1.0)
//   Created: 2025-12-19 09:52:42Z
//   This is an auto-generated file. Do not modify.
// </auto-generated>

namespace Toarnbeike.Unions.Extensions;

/// <summary>
/// Project: extension methods to project (transform) union values.
/// This is a union modifying operation, the resulting union has a different type compared to the original.
/// For type perserving operation, prefer <see cref="MapExtensions"/>
/// </summary>
/// <remarks> 
/// This file deals with full projections, transforming all possible types of the union at once.
/// For partial transforming, see the other part of this partial class.
/// </remarks>
public static partial class ProjectExtensions
{
    #region Projection Extensions for Union<T1, T2>

    extension<T1, T2>(Union<T1, T2> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       public Union<TNew1, TNew2> Project<TNew1, TNew2>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           
           return union.Match(
              t1 => Union<TNew1, TNew2>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2>.FromT2(projectT2(t2))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       public Task<Union<TNew1, TNew2>> ProjectAsync<TNew1, TNew2>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2>.FromT2(await projectT2Async(t2).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2>(Task<Union<T1, T2>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       public async Task<Union<TNew1, TNew2>> Project<TNew1, TNew2>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       public async Task<Union<TNew1, TNew2>> ProjectAsync<TNew1, TNew2>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async).ConfigureAwait(false);
       }
    }

    #endregion

    #region Projection Extensions for Union<T1, T2, T3>

    extension<T1, T2, T3>(Union<T1, T2, T3> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       public Union<TNew1, TNew2, TNew3> Project<TNew1, TNew2, TNew3>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           ArgumentNullException.ThrowIfNull(projectT3);
           
           return union.Match(
              t1 => Union<TNew1, TNew2, TNew3>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2, TNew3>.FromT2(projectT2(t2)),
              t3 => Union<TNew1, TNew2, TNew3>.FromT3(projectT3(t3))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       public Task<Union<TNew1, TNew2, TNew3>> ProjectAsync<TNew1, TNew2, TNew3>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           ArgumentNullException.ThrowIfNull(projectT3Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2, TNew3>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2, TNew3>.FromT2(await projectT2Async(t2).ConfigureAwait(false)),
              async t3 => Union<TNew1, TNew2, TNew3>.FromT3(await projectT3Async(t3).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2, T3>(Task<Union<T1, T2, T3>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3>> Project<TNew1, TNew2, TNew3>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2, projectT3);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3>> ProjectAsync<TNew1, TNew2, TNew3>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async, projectT3Async).ConfigureAwait(false);
       }
    }

    #endregion

    #region Projection Extensions for Union<T1, T2, T3, T4>

    extension<T1, T2, T3, T4>(Union<T1, T2, T3, T4> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       public Union<TNew1, TNew2, TNew3, TNew4> Project<TNew1, TNew2, TNew3, TNew4>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           ArgumentNullException.ThrowIfNull(projectT3);
           ArgumentNullException.ThrowIfNull(projectT4);
           
           return union.Match(
              t1 => Union<TNew1, TNew2, TNew3, TNew4>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2, TNew3, TNew4>.FromT2(projectT2(t2)),
              t3 => Union<TNew1, TNew2, TNew3, TNew4>.FromT3(projectT3(t3)),
              t4 => Union<TNew1, TNew2, TNew3, TNew4>.FromT4(projectT4(t4))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       public Task<Union<TNew1, TNew2, TNew3, TNew4>> ProjectAsync<TNew1, TNew2, TNew3, TNew4>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           ArgumentNullException.ThrowIfNull(projectT3Async);
           ArgumentNullException.ThrowIfNull(projectT4Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2, TNew3, TNew4>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2, TNew3, TNew4>.FromT2(await projectT2Async(t2).ConfigureAwait(false)),
              async t3 => Union<TNew1, TNew2, TNew3, TNew4>.FromT3(await projectT3Async(t3).ConfigureAwait(false)),
              async t4 => Union<TNew1, TNew2, TNew3, TNew4>.FromT4(await projectT4Async(t4).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2, T3, T4>(Task<Union<T1, T2, T3, T4>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4>> Project<TNew1, TNew2, TNew3, TNew4>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2, projectT3, projectT4);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4>> ProjectAsync<TNew1, TNew2, TNew3, TNew4>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async, projectT3Async, projectT4Async).ConfigureAwait(false);
       }
    }

    #endregion

    #region Projection Extensions for Union<T1, T2, T3, T4, T5>

    extension<T1, T2, T3, T4, T5>(Union<T1, T2, T3, T4, T5> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       public Union<TNew1, TNew2, TNew3, TNew4, TNew5> Project<TNew1, TNew2, TNew3, TNew4, TNew5>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           ArgumentNullException.ThrowIfNull(projectT3);
           ArgumentNullException.ThrowIfNull(projectT4);
           ArgumentNullException.ThrowIfNull(projectT5);
           
           return union.Match(
              t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT2(projectT2(t2)),
              t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT3(projectT3(t3)),
              t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT4(projectT4(t4)),
              t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT5(projectT5(t5))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       public Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           ArgumentNullException.ThrowIfNull(projectT3Async);
           ArgumentNullException.ThrowIfNull(projectT4Async);
           ArgumentNullException.ThrowIfNull(projectT5Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT2(await projectT2Async(t2).ConfigureAwait(false)),
              async t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT3(await projectT3Async(t3).ConfigureAwait(false)),
              async t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT4(await projectT4Async(t4).ConfigureAwait(false)),
              async t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5>.FromT5(await projectT5Async(t5).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2, T3, T4, T5>(Task<Union<T1, T2, T3, T4, T5>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5>> Project<TNew1, TNew2, TNew3, TNew4, TNew5>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2, projectT3, projectT4, projectT5);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async, projectT3Async, projectT4Async, projectT5Async).ConfigureAwait(false);
       }
    }

    #endregion

    #region Projection Extensions for Union<T1, T2, T3, T4, T5, T6>

    extension<T1, T2, T3, T4, T5, T6>(Union<T1, T2, T3, T4, T5, T6> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       /// <param name="projectT6">The projection function if the union is in the T6 state. </param>
       public Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6> Project<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5, Func<T6,TNew6> projectT6)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           ArgumentNullException.ThrowIfNull(projectT3);
           ArgumentNullException.ThrowIfNull(projectT4);
           ArgumentNullException.ThrowIfNull(projectT5);
           ArgumentNullException.ThrowIfNull(projectT6);
           
           return union.Match(
              t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT2(projectT2(t2)),
              t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT3(projectT3(t3)),
              t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT4(projectT4(t4)),
              t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT5(projectT5(t5)),
              t6 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT6(projectT6(t6))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       /// <param name="projectT6Async">The async projection function if the union is in the T6 state. </param>
       public Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async, Func<T6, Task<TNew6>> projectT6Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           ArgumentNullException.ThrowIfNull(projectT3Async);
           ArgumentNullException.ThrowIfNull(projectT4Async);
           ArgumentNullException.ThrowIfNull(projectT5Async);
           ArgumentNullException.ThrowIfNull(projectT6Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT2(await projectT2Async(t2).ConfigureAwait(false)),
              async t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT3(await projectT3Async(t3).ConfigureAwait(false)),
              async t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT4(await projectT4Async(t4).ConfigureAwait(false)),
              async t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT5(await projectT5Async(t5).ConfigureAwait(false)),
              async t6 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>.FromT6(await projectT6Async(t6).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2, T3, T4, T5, T6>(Task<Union<T1, T2, T3, T4, T5, T6>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       /// <param name="projectT6">The projection function if the union is in the T6 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>> Project<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5, Func<T6,TNew6> projectT6)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2, projectT3, projectT4, projectT5, projectT6);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       /// <param name="projectT6Async">The async projection function if the union is in the T6 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async, Func<T6, Task<TNew6>> projectT6Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async, projectT3Async, projectT4Async, projectT5Async, projectT6Async).ConfigureAwait(false);
       }
    }

    #endregion

    #region Projection Extensions for Union<T1, T2, T3, T4, T5, T6, T7>

    extension<T1, T2, T3, T4, T5, T6, T7>(Union<T1, T2, T3, T4, T5, T6, T7> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       /// <param name="projectT6">The projection function if the union is in the T6 state. </param>
       /// <param name="projectT7">The projection function if the union is in the T7 state. </param>
       public Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7> Project<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5, Func<T6,TNew6> projectT6, Func<T7,TNew7> projectT7)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           ArgumentNullException.ThrowIfNull(projectT3);
           ArgumentNullException.ThrowIfNull(projectT4);
           ArgumentNullException.ThrowIfNull(projectT5);
           ArgumentNullException.ThrowIfNull(projectT6);
           ArgumentNullException.ThrowIfNull(projectT7);
           
           return union.Match(
              t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT2(projectT2(t2)),
              t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT3(projectT3(t3)),
              t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT4(projectT4(t4)),
              t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT5(projectT5(t5)),
              t6 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT6(projectT6(t6)),
              t7 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT7(projectT7(t7))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       /// <param name="projectT6Async">The async projection function if the union is in the T6 state. </param>
       /// <param name="projectT7Async">The async projection function if the union is in the T7 state. </param>
       public Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async, Func<T6, Task<TNew6>> projectT6Async, Func<T7, Task<TNew7>> projectT7Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           ArgumentNullException.ThrowIfNull(projectT3Async);
           ArgumentNullException.ThrowIfNull(projectT4Async);
           ArgumentNullException.ThrowIfNull(projectT5Async);
           ArgumentNullException.ThrowIfNull(projectT6Async);
           ArgumentNullException.ThrowIfNull(projectT7Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT2(await projectT2Async(t2).ConfigureAwait(false)),
              async t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT3(await projectT3Async(t3).ConfigureAwait(false)),
              async t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT4(await projectT4Async(t4).ConfigureAwait(false)),
              async t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT5(await projectT5Async(t5).ConfigureAwait(false)),
              async t6 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT6(await projectT6Async(t6).ConfigureAwait(false)),
              async t7 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>.FromT7(await projectT7Async(t7).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2, T3, T4, T5, T6, T7>(Task<Union<T1, T2, T3, T4, T5, T6, T7>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       /// <param name="projectT6">The projection function if the union is in the T6 state. </param>
       /// <param name="projectT7">The projection function if the union is in the T7 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>> Project<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5, Func<T6,TNew6> projectT6, Func<T7,TNew7> projectT7)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2, projectT3, projectT4, projectT5, projectT6, projectT7);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       /// <param name="projectT6Async">The async projection function if the union is in the T6 state. </param>
       /// <param name="projectT7Async">The async projection function if the union is in the T7 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async, Func<T6, Task<TNew6>> projectT6Async, Func<T7, Task<TNew7>> projectT7Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async, projectT3Async, projectT4Async, projectT5Async, projectT6Async, projectT7Async).ConfigureAwait(false);
       }
    }

    #endregion

    #region Projection Extensions for Union<T1, T2, T3, T4, T5, T6, T7, T8>

    extension<T1, T2, T3, T4, T5, T6, T7, T8>(Union<T1, T2, T3, T4, T5, T6, T7, T8> union)
    {
       /// <summary>
       /// Apply projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       /// <param name="projectT6">The projection function if the union is in the T6 state. </param>
       /// <param name="projectT7">The projection function if the union is in the T7 state. </param>
       /// <param name="projectT8">The projection function if the union is in the T8 state. </param>
       public Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8> Project<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5, Func<T6,TNew6> projectT6, Func<T7,TNew7> projectT7, Func<T8,TNew8> projectT8)
       {
           ArgumentNullException.ThrowIfNull(projectT1);
           ArgumentNullException.ThrowIfNull(projectT2);
           ArgumentNullException.ThrowIfNull(projectT3);
           ArgumentNullException.ThrowIfNull(projectT4);
           ArgumentNullException.ThrowIfNull(projectT5);
           ArgumentNullException.ThrowIfNull(projectT6);
           ArgumentNullException.ThrowIfNull(projectT7);
           ArgumentNullException.ThrowIfNull(projectT8);
           
           return union.Match(
              t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT1(projectT1(t1)),
              t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT2(projectT2(t2)),
              t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT3(projectT3(t3)),
              t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT4(projectT4(t4)),
              t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT5(projectT5(t5)),
              t6 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT6(projectT6(t6)),
              t7 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT7(projectT7(t7)),
              t8 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT8(projectT8(t8))
           );
       }

       /// <summary>
       /// Apply async projecting functions to the value stored in the union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       /// <param name="projectT6Async">The async projection function if the union is in the T6 state. </param>
       /// <param name="projectT7Async">The async projection function if the union is in the T7 state. </param>
       /// <param name="projectT8Async">The async projection function if the union is in the T8 state. </param>
       public Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async, Func<T6, Task<TNew6>> projectT6Async, Func<T7, Task<TNew7>> projectT7Async, Func<T8, Task<TNew8>> projectT8Async)
       {
           ArgumentNullException.ThrowIfNull(projectT1Async);
           ArgumentNullException.ThrowIfNull(projectT2Async);
           ArgumentNullException.ThrowIfNull(projectT3Async);
           ArgumentNullException.ThrowIfNull(projectT4Async);
           ArgumentNullException.ThrowIfNull(projectT5Async);
           ArgumentNullException.ThrowIfNull(projectT6Async);
           ArgumentNullException.ThrowIfNull(projectT7Async);
           ArgumentNullException.ThrowIfNull(projectT8Async);
           
           return union.MatchAsync(
              async t1 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT1(await projectT1Async(t1).ConfigureAwait(false)),
              async t2 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT2(await projectT2Async(t2).ConfigureAwait(false)),
              async t3 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT3(await projectT3Async(t3).ConfigureAwait(false)),
              async t4 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT4(await projectT4Async(t4).ConfigureAwait(false)),
              async t5 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT5(await projectT5Async(t5).ConfigureAwait(false)),
              async t6 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT6(await projectT6Async(t6).ConfigureAwait(false)),
              async t7 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT7(await projectT7Async(t7).ConfigureAwait(false)),
              async t8 => Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>.FromT8(await projectT8Async(t8).ConfigureAwait(false))
           );
       }
    }
    
    extension<T1, T2, T3, T4, T5, T6, T7, T8>(Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> unionTask)
    {

       /// <summary>
       /// Apply projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1">The projection function if the union is in the T1 state. </param>
       /// <param name="projectT2">The projection function if the union is in the T2 state. </param>
       /// <param name="projectT3">The projection function if the union is in the T3 state. </param>
       /// <param name="projectT4">The projection function if the union is in the T4 state. </param>
       /// <param name="projectT5">The projection function if the union is in the T5 state. </param>
       /// <param name="projectT6">The projection function if the union is in the T6 state. </param>
       /// <param name="projectT7">The projection function if the union is in the T7 state. </param>
       /// <param name="projectT8">The projection function if the union is in the T8 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>> Project<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>(Func<T1,TNew1> projectT1, Func<T2,TNew2> projectT2, Func<T3,TNew3> projectT3, Func<T4,TNew4> projectT4, Func<T5,TNew5> projectT5, Func<T6,TNew6> projectT6, Func<T7,TNew7> projectT7, Func<T8,TNew8> projectT8)
       {
           var union = await unionTask.ConfigureAwait(false);
           return union.Project(projectT1, projectT2, projectT3, projectT4, projectT5, projectT6, projectT7, projectT8);
       }            

       /// <summary>
       /// Apply async projection functions to the value stored in the task union based on its current state.
       /// </summary>
       /// <param name="projectT1Async">The async projection function if the union is in the T1 state. </param>
       /// <param name="projectT2Async">The async projection function if the union is in the T2 state. </param>
       /// <param name="projectT3Async">The async projection function if the union is in the T3 state. </param>
       /// <param name="projectT4Async">The async projection function if the union is in the T4 state. </param>
       /// <param name="projectT5Async">The async projection function if the union is in the T5 state. </param>
       /// <param name="projectT6Async">The async projection function if the union is in the T6 state. </param>
       /// <param name="projectT7Async">The async projection function if the union is in the T7 state. </param>
       /// <param name="projectT8Async">The async projection function if the union is in the T8 state. </param>
       public async Task<Union<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>> ProjectAsync<TNew1, TNew2, TNew3, TNew4, TNew5, TNew6, TNew7, TNew8>(Func<T1, Task<TNew1>> projectT1Async, Func<T2, Task<TNew2>> projectT2Async, Func<T3, Task<TNew3>> projectT3Async, Func<T4, Task<TNew4>> projectT4Async, Func<T5, Task<TNew5>> projectT5Async, Func<T6, Task<TNew6>> projectT6Async, Func<T7, Task<TNew7>> projectT7Async, Func<T8, Task<TNew8>> projectT8Async)
       {
           var union = await unionTask.ConfigureAwait(false);
           return await union.ProjectAsync(projectT1Async, projectT2Async, projectT3Async, projectT4Async, projectT5Async, projectT6Async, projectT7Async, projectT8Async).ConfigureAwait(false);
       }
    }

    #endregion
}