# nullable enable

// <auto-generated>
//   This file was generated by Toarnbeike.Unions.StaticGenerator.
//   Generator: TapExtensionsGenerator (v. 1.0.0)
//   Created: 2025-12-17 16:17:36Z
//   This is an auto-generated file. Do not modify.
// </auto-generated>

namespace Toarnbeike.Unions.Extensions;

/// <summary>
/// Tap: extension methods to apply a side effect when the union is in a given state.
/// Returns the original union for fluent chaining.
/// </summary>
public static class TapExtensions
{
    #region Tap Extensions for Union<T1, T2>

    extension<T1, T2>(Union<T1, T2> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2>(Task<Union<T1, T2>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion

    #region Tap Extensions for Union<T1, T2, T3>

    extension<T1, T2, T3>(Union<T1, T2, T3> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3> TapT3(Action<T3> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT3(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT3Async(Func<T3, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT3(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2, T3>(Task<Union<T1, T2, T3>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT3(Action<T3> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT3(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3>> TapT3Async(Func<T3, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT3Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion

    #region Tap Extensions for Union<T1, T2, T3, T4>

    extension<T1, T2, T3, T4>(Union<T1, T2, T3, T4> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4> TapT3(Action<T3> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT3(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4> TapT4(Action<T4> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT4(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT3Async(Func<T3, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT3(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT4Async(Func<T4, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT4(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2, T3, T4>(Task<Union<T1, T2, T3, T4>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT3(Action<T3> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT3(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT4(Action<T4> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT4(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT3Async(Func<T3, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT3Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4>> TapT4Async(Func<T4, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT4Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion

    #region Tap Extensions for Union<T1, T2, T3, T4, T5>

    extension<T1, T2, T3, T4, T5>(Union<T1, T2, T3, T4, T5> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5> TapT3(Action<T3> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT3(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5> TapT4(Action<T4> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT4(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5> TapT5(Action<T5> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT5(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT3Async(Func<T3, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT3(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT4Async(Func<T4, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT4(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT5Async(Func<T5, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT5(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2, T3, T4, T5>(Task<Union<T1, T2, T3, T4, T5>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT3(Action<T3> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT3(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT4(Action<T4> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT4(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT5(Action<T5> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT5(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT3Async(Func<T3, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT3Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT4Async(Func<T4, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT4Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5>> TapT5Async(Func<T5, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT5Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion

    #region Tap Extensions for Union<T1, T2, T3, T4, T5, T6>

    extension<T1, T2, T3, T4, T5, T6>(Union<T1, T2, T3, T4, T5, T6> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6> TapT3(Action<T3> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT3(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6> TapT4(Action<T4> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT4(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6> TapT5(Action<T5> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT5(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T6 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6> TapT6(Action<T6> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT6(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT3Async(Func<T3, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT3(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT4Async(Func<T4, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT4(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT5Async(Func<T5, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT5(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T6 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT6Async(Func<T6, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT6(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2, T3, T4, T5, T6>(Task<Union<T1, T2, T3, T4, T5, T6>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT3(Action<T3> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT3(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT4(Action<T4> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT4(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT5(Action<T5> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT5(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T6 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT6(Action<T6> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT6(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT3Async(Func<T3, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT3Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT4Async(Func<T4, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT4Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT5Async(Func<T5, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT5Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T6 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6>> TapT6Async(Func<T6, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT6Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion

    #region Tap Extensions for Union<T1, T2, T3, T4, T5, T6, T7>

    extension<T1, T2, T3, T4, T5, T6, T7>(Union<T1, T2, T3, T4, T5, T6, T7> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT3(Action<T3> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT3(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT4(Action<T4> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT4(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT5(Action<T5> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT5(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T6 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT6(Action<T6> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT6(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T7 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7> TapT7(Action<T7> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT7(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT3Async(Func<T3, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT3(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT4Async(Func<T4, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT4(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT5Async(Func<T5, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT5(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T6 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT6Async(Func<T6, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT6(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T7 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT7Async(Func<T7, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT7(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2, T3, T4, T5, T6, T7>(Task<Union<T1, T2, T3, T4, T5, T6, T7>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT3(Action<T3> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT3(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT4(Action<T4> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT4(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT5(Action<T5> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT5(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T6 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT6(Action<T6> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT6(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T7 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT7(Action<T7> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT7(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT3Async(Func<T3, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT3Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT4Async(Func<T4, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT4Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT5Async(Func<T5, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT5Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T6 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT6Async(Func<T6, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT6Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T7 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7>> TapT7Async(Func<T7, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT7Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion

    #region Tap Extensions for Union<T1, T2, T3, T4, T5, T6, T7, T8>

    extension<T1, T2, T3, T4, T5, T6, T7, T8>(Union<T1, T2, T3, T4, T5, T6, T7, T8> union)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT1(Action<T1> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT1(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT2(Action<T2> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT2(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT3(Action<T3> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT3(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT4(Action<T4> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT4(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT5(Action<T5> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT5(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T6 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT6(Action<T6> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT6(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T7 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT7(Action<T7> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT7(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the union if it is in the T8 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public Union<T1, T2, T3, T4, T5, T6, T7, T8> TapT8(Action<T8> handle)
        {
            ArgumentNullException.ThrowIfNull(handle);

            if (union.TryGetT8(out var value))
            {
                handle(value);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT1Async(Func<T1, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT1(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT2Async(Func<T2, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT2(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT3Async(Func<T3, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT3(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT4Async(Func<T4, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT4(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT5Async(Func<T5, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT5(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T6 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT6Async(Func<T6, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT6(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T7 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT7Async(Func<T7, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT7(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the union if it is in the T8 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT8Async(Func<T8, Task> handleAsync)
        {
            ArgumentNullException.ThrowIfNull(handleAsync);

            if (union.TryGetT8(out var value))
            {
                await handleAsync(value).ConfigureAwait(false);
            }
            return union;
        }
    }
    
    extension<T1, T2, T3, T4, T5, T6, T7, T8>(Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> unionTask)
    {

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT1(Action<T1> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT1(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT2(Action<T2> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT2(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT3(Action<T3> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT3(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT4(Action<T4> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT4(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT5(Action<T5> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT5(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T6 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT6(Action<T6> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT6(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T7 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT7(Action<T7> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT7(handle);
        }

        /// <summary>
        /// Handle a side effect function to the value stored in the task union if it is in the T8 state.
        /// </summary>
        /// <param name="handle">The side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT8(Action<T8> handle)
        {
            var union = await unionTask.ConfigureAwait(false);
            return union.TapT8(handle);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T1 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT1Async(Func<T1, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT1Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T2 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT2Async(Func<T2, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT2Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T3 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT3Async(Func<T3, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT3Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T4 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT4Async(Func<T4, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT4Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T5 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT5Async(Func<T5, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT5Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T6 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT6Async(Func<T6, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT6Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T7 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT7Async(Func<T7, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT7Async(handleAsync).ConfigureAwait(false);
        }

        /// <summary>
        /// Handle an async side effect function to the value stored in the task union if it is in the T8 state.
        /// </summary>
        /// <param name="handleAsync">The async side effect to handle.</param>
        public async Task<Union<T1, T2, T3, T4, T5, T6, T7, T8>> TapT8Async(Func<T8, Task> handleAsync)
        {
            var union = await unionTask.ConfigureAwait(false);
            return await union.TapT8Async(handleAsync).ConfigureAwait(false);
        }
    }

    #endregion
}