using Toarnbeike.Unions.Utilities;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates the union.Bind extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
/// <remarks> The BindTExtensions are generated in <see cref="BindFullExtensionsGenerator"/></remarks>
internal static class BindPartialExtensionsGenerator
{
    public static string Generate(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(BindPartialExtensionsGenerator))}}

            namespace Toarnbeike.Unions.Generic.Extensions;

            /// <summary>
            /// Bind: extension methods to bind (flatmap) union values.
            /// This gives the ability to transform a union case into another union case.
            /// </summary>
            /// <remarks> 
            /// This file deals with partial binds, binding one specific case of the union.
            /// For full transforming, see the other part of this partial class.
            /// </remarks>
            public static partial class BindExtensions
            {{{string.Join("\n", arities.Select(GenerateBind))}}
            }
            """;
    }

    private static string GenerateBind(int arity)
    {
        var arities = Enumerable.Range(1, arity).ToArray();
        var genericArgs = $"<{string.Join(", ", arities.Select(i => $"T{i}"))}>";
        return $$"""

                     #region Bind Extensions for Union{{genericArgs}}

                     extension{{genericArgs}}(Union{{genericArgs}} union)
                     {
                 {{string.Join("\n", arities.Select(i => BindT(i, genericArgs)))}}
                 {{string.Join("\n", arities.Select(i => BindAsyncT(i, genericArgs)))}}
                     }
                     
                     extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                     {
                 {{string.Join("\n", arities.Select(i => TaskBindT(i, genericArgs)))}}
                 {{string.Join("\n", arities.Select(i => TaskBindAsyncT(i, genericArgs)))}}
                     }

                     #endregion
                 """;
    }

    private static string BindT(int arity, string genericArgs)
    {
        return $$"""

                         /// <summary>
                         /// Apply a binding function to the value stored in the union if it is in the T{{arity}} state.
                         /// </summary>
                         /// <param name="bind">The binding function to apply.</param>
                         public Union{{genericArgs}} BindT{{arity}}(Func<T{{arity}}, Union{{genericArgs}}> bind)
                         {
                             ArgumentNullException.ThrowIfNull(bind);

                             return union.TryGetT{{arity}}(out var value)
                                 ? bind(value)
                                 : union;
                         }
                 """;
    }

    private static string BindAsyncT(int arity, string genericArgs)
    {
        return $$"""

                         /// <summary>
                         /// Apply an async binding function to the value stored in the union if it is in the T{{arity}} state.
                         /// </summary>
                         /// <param name="bindAsync">The binding function to apply.</param>
                         public Task<Union{{genericArgs}}> BindT{{arity}}Async(Func<T{{arity}}, Task<Union{{genericArgs}}>> bindAsync)
                         {
                             ArgumentNullException.ThrowIfNull(bindAsync);

                             return union.TryGetT{{arity}}(out var value)
                                 ? bindAsync(value)
                                 : Task.FromResult(union);
                         }
                 """;
    }

    private static string TaskBindT(int arity, string genericArgs)
    {
        return $$"""

                         /// <summary>
                         /// Apply a binding function to the value stored in the task union if it is in the T{{arity}} state.
                         /// </summary>
                         /// <param name="bind">The binding function to apply.</param>
                         public async Task<Union{{genericArgs}}> BindT{{arity}}(Func<T{{arity}}, Union{{genericArgs}}> bind)
                         {
                             var union = await unionTask.ConfigureAwait(false);
                             return union.BindT{{arity}}(bind);
                         }
                 """;
    }

    private static string TaskBindAsyncT(int arity, string genericArgs)
    {
        return $$"""

                         /// <summary>
                         /// Apply an async binding function to the value stored in the task union if it is in the T{{arity}} state.
                         /// </summary>
                         /// <param name="bindAsync">The binding function to apply.</param>
                         public async Task<Union{{genericArgs}}> BindT{{arity}}Async(Func<T{{arity}}, Task<Union{{genericArgs}}>> bindAsync)
                         {
                             var union = await unionTask.ConfigureAwait(false);
                             return await union.BindT{{arity}}Async(bindAsync).ConfigureAwait(false);
                         }
                 """;
    }
}
