using Toarnbeike.Unions.Utilities;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates the union.MapT extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
/// <remarks> The MapExtensions are generated in <see cref="MapFullExtensionsGenerator"/></remarks>
internal static class MapPartialExtensionsGenerator
{
    public static string Generate(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(MapPartialExtensionsGenerator))}}
            
            namespace Toarnbeike.Unions.Generic.Extensions;

            /// <summary>
            /// Map: extension methods to map (transform) union values.
            /// </summary>
            /// <remarks> 
            /// This file deals with partial mappings, transforming one specific case of the union.
            /// For full mappings, see the other part of this partial class.
            /// </remarks>
            public static partial class MapExtensions
            {{{string.Join("\n", arities.Select(GenerateMaps))}}
            }
            """;
    }

    private static string GenerateMaps(int arity)
    {
        var arities = Enumerable.Range(1, arity).ToArray();
        var genericArgs = $"<{string.Join(", ", arities.Select(i => $"T{i}"))}>";
        return $$"""

                     #region Mapion Extensions for Union{{genericArgs}}

                     extension{{genericArgs}}(Union{{genericArgs}} union)
                     {
                 {{string.Join("\n", arities.Select(i => MapT(i, arities)))}}
                 {{string.Join("\n", arities.Select(i => MapAsyncT(i, arities)))}}
                     }
                     
                     extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                     {
                 {{string.Join("\n", arities.Select(i => TaskMapT(i, arities)))}}
                 {{string.Join("\n", arities.Select(i => TaskMapAsyncT(i, arities)))}}
                     }

                     #endregion
                 """;
    }

    private static string MapT(int arity, int[] arities)
    {
        var newArgs = $"<{string.Join(", ", arities.Select(i => i == arity ? "TNew" : $"T{i}"))}>";
        return $$"""

                        /// <summary>
                        /// Apply a mapping function to the value stored in the union if it is in the T{{arity}} state.
                        /// </summary>
                        /// <param name="map">The mapping function to apply.</param>
                        public Union{{newArgs}} MapT{{arity}}<TNew>(Func<T{{arity}}, TNew> map)
                        {
                            ArgumentNullException.ThrowIfNull(mapping);

                            return union.Match(
                               {{string.Join(",\n              ", arities.Select(i => MatchLine(i, newArgs, i == arity)))}}
                            );
                        }
                 """;
    }

    private static string MapAsyncT(int arity, int[] arities)
    {
        var newArgs = $"<{string.Join(", ", arities.Select(i => i == arity ? "TNew" : $"T{i}"))}>";
        return $$"""

                        /// <summary>
                        /// Apply an async mapping function to the value stored in the union if it is in the T{{arity}} state.
                        /// </summary>
                        /// <param name="mapAsync">The mapping function to apply.</param>
                        public Task<Union{{newArgs}}> MapT{{arity}}Async<TNew>(Func<T{{arity}}, Task<TNew>> mapAsync)
                        {
                            ArgumentNullException.ThrowIfNull(mappingAsync);

                            return union.MatchAsync(
                               {{string.Join(",\n              ", arities.Select(i => MatchLineAsync(i, newArgs, i == arity)))}}
                            );
                        }                           
                 """;
    }

    private static string TaskMapT(int arity, int[] arities)
    {
        var newArgs = $"<{string.Join(", ", arities.Select(i => i == arity ? "TNew" : $"T{i}"))}>";
        return $$"""

                        /// <summary>
                        /// Apply a mapping function to the value stored in the task union if it is in the T{arity} state.
                        /// </summary>
                        /// <param name="mapping">The mapping function to apply.</param>
                        public async Task<Union{{newArgs}}> MapT{{arity}}<TNew>(Func<T{{arity}}, TNew> mapping)
                        {
                            var union = await unionTask.ConfigureAwait(false);
                            return union.MapT{{arity}}(mapping);
                        }
                 """;
    }

    private static string TaskMapAsyncT(int arity, int[] arities)
    {
        var newArgs = $"<{string.Join(", ", arities.Select(i => i == arity ? "TNew" : $"T{i}"))}>";
        return $$"""

                        /// <summary>
                        /// Apply an async mapping function to the value stored in the task union if it is in the T{arity} state.
                        /// </summary>
                        /// <param name="mappingAsync">The mapping function to apply.</param>
                        public async Task<Union{{newArgs}}> MapT{{arity}}Async<TNew>(Func<T{{arity}}, Task<TNew>> mappingAsync)
                        {
                            var union = await unionTask.ConfigureAwait(false);
                            return await union.MapT{{arity}}Async(mappingAsync).ConfigureAwait(false);
                        }
                 """;
    }

    private static string MatchLine(int arity, string newArgs, bool isCurrent)
    {
        return isCurrent
            ? $"t{arity} => Union{newArgs}.FromT{arity}(map(t{arity}))"
            : $"Union{newArgs}.FromT{arity}";
    }

    private static string MatchLineAsync(int arity, string newArgs, bool isCurrent)
    {
        return isCurrent
            ? $"    async t{arity} => Union{newArgs}.FromT{arity}(await mapAsync(t{arity}).ConfigureAwait(false))"
            : $"    t{arity} => Task.FromResult(Union{newArgs}.FromT{arity}(t{arity}))";
    }
}