using Toarnbeike.Unions.Utilities;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates the union.Match extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class MatchExtensionsGenerator
{
    public static string Generate(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(MatchExtensionsGenerator))}}
            
            namespace Toarnbeike.Unions.Extensions;

            /// <summary>
            /// Match: extension methods to match (fold; convert to result) union values.
            /// </summary>
            public static class MatchExtensions
            {{{string.Join("\n", arities.Select(GenerateMatch))}}
            }
            """;
    }

    private static string GenerateMatch(int arity)
    {
        var collection = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{string.Join(", ", collection.Select(i => $"T{i}"))}>";

        return $$"""

                     #region Match Extensions for Union{{genericArgs}}

                     extension{{genericArgs}}(Union{{genericArgs}} union)
                     {
                         /// <summary>
                         /// Matches the value stored in the union and invokes the corresponding function based on its type.
                         /// </summary>
                         /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                         {{string.Join("\n        ", collection.Select(i => ParamXmlComments(i, false)))}}
                         /// <returns>The result of invoking the appropriate match function.</returns>
                         /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                         public TResult Match<TResult>({{string.Join(", ", collection.Select(i => $"Func<T{i}, TResult> onT{i}"))}})
                         {
                             {{string.Join("\n            ", collection.Select(i => $"ArgumentNullException.ThrowIfNull(onT{i});"))}}
                 
                             return union.Index switch
                             {
                                {{string.Join("\n               ", collection.Select(i => SwitchLine(i, false)))}}
                                _ => throw new InvalidOperationException($"Union index {union.Index} is invalid.")
                             };
                         }
                         
                         /// <summary>
                         /// Matches the value stored in the union and invokes the corresponding async function based on its type.
                         /// </summary>
                         /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                         {{string.Join("\n        ", collection.Select(i => ParamXmlComments(i, true)))}}
                         /// <returns>The result of invoking the appropriate match function.</returns>
                         /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                         public Task<TResult> MatchAsync<TResult>({{string.Join(", ", collection.Select(i => $"Func<T{i}, Task<TResult>> onT{i}Async"))}})
                         {
                             {{string.Join("\n            ", collection.Select(i => $"ArgumentNullException.ThrowIfNull(onT{i}Async);"))}}
                 
                             return union.Index switch
                             {
                                {{string.Join("\n               ", collection.Select(i => SwitchLine(i, true)))}}
                                _ => Task.FromException<TResult>(new InvalidOperationException($"Union index {union.Index} is invalid."))
                             };
                         }
                     }
                     
                     extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                     {
                         /// <summary>
                         /// Matches the value stored in the union and invokes the corresponding function based on its type.
                         /// </summary>
                         /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                         {{string.Join("\n        ", collection.Select(i => ParamXmlComments(i, false)))}}
                         /// <returns>The result of invoking the appropriate match function.</returns>
                         /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                         public async Task<TResult> Match<TResult>({{string.Join(", ", collection.Select(i => $"Func<T{i}, TResult> onT{i}"))}})
                         {
                             var union = await unionTask.ConfigureAwait(false);
                             return union.Match({{string.Join(", ", collection.Select(i => $"onT{i}"))}});
                        }
                         
                         /// <summary>
                         /// Matches the value stored in the union and invokes the corresponding async function based on its type.
                         /// </summary>
                         /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                         {{string.Join("\n        ", collection.Select(i => ParamXmlComments(i, true)))}}
                         /// <returns>The result of invoking the appropriate match function.</returns>
                         /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                         public async Task<TResult> MatchAsync<TResult>({{string.Join(", ", collection.Select(i => $"Func<T{i}, Task<TResult>> onT{i}Async"))}})
                         {
                             var union = await unionTask.ConfigureAwait(false);
                             return await union.MatchAsync({{string.Join(", ", collection.Select(i => $"onT{i}Async"))}}).ConfigureAwait(false);
                         }
                     }

                     #endregion
                 """;
    }

    private static string ParamXmlComments(int arity, bool async)
    {
        var asyncSuffix = async ? "Async" : "";
        var asyncComment = async ? "async " : "";
        return $"/// <param name=\"onT{arity}{asyncSuffix}\">The {asyncComment}function to invoke when the union holds a value of type T{arity}.</param>";
    }

    private static string SwitchLine(int arity, bool async)
    {
        return $"{arity} => onT{arity}{(async ? "Async" : "")}(union.AsT{arity}),";
    }
}
