using Toarnbeike.Unions.Utilities;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates the Union.SelectT and Union.Partition extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class PartitionExtensionsGenerator
{
    public static string Generate(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(PartitionExtensionsGenerator))}}

            using Toarnbeike.Unions.Extensions;

            namespace Toarnbeike.Unions.Collections;

            /// <summary>
            /// Partition: extension methods to partition collections of unions into collections of their constituent types.
            /// </summary>
            public static class PartitionExtensions
            {{{string.Join("\n", arities.Select(GeneratePartition))}}
            }
            """;
    }

    private static string GeneratePartition(int arity)
    {
        var arityList = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{string.Join(", ", arityList.Select(i => $"T{i}"))}>";

        return $$"""

                     #region Partition Extensions for Union{{genericArgs}}
                     extension{{genericArgs}}(IEnumerable<Union{{genericArgs}}> source)
                     {
                 {{string.Join("\n", arityList.Select(SelectT))}}

                         /// <summary>
                         /// Partitions a collection of unions into separate collections for each type in the union.
                         /// </summary>
                         /// <param name="source">The source collection of unions.</param>
                         /// <returns>A tuple containing a list for each type in the union.</returns>
                         public ({{string.Join(", ", arityList.Select(i => $"IReadOnlyList<T{i}> T{i}s"))}}) Partition()
                         {
                             ArgumentNullException.ThrowIfNull(source);

                             {{string.Join("\n            ", arityList.Select(i => $"var t{i}Set = new List<T{i}>();"))}}

                             foreach (var union in source)
                             {
                                 union.Switch({{string.Join(", ", arityList.Select(i => $"t{i}Set.Add"))}});
                             }

                             return ({{string.Join(", ", arityList.Select(i => $"t{i}Set"))}});
                         }
                     }

                     #endregion
                 """;
    }

    private static string SelectT(int arity)
    {
        return $$"""

                         /// <summary>
                         /// Select all elements of type T{{arity}} from the collection of unions.
                         /// </summary>
                         public IEnumerable<T{{arity}}> SelectT{{arity}}()
                         {
                             ArgumentNullException.ThrowIfNull(source);

                             return source.Where(union => union.IsT{{arity}}).Select(union => union.AsT{{arity}});
                         }
                  """;
    }
}
