using Toarnbeike.Unions.Utilities;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates the union.Project extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
/// <remarks> The ProjectTExtenions are generated in <see cref="ProjectTExtensionsGenerator"/></remarks>
internal static class ProjectFullExtensionsGenerator
{
    public static string Generate(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(ProjectFullExtensionsGenerator))}}
            
            namespace Toarnbeike.Unions.Extensions;

            /// <summary>
            /// Project: extension methods to project (transform) union values.
            /// This is a union modifying operation, the resulting union has a different type compared to the original.
            /// For type perserving operation, prefer <see cref="MapExtensions"/>
            /// </summary>
            /// <remarks> 
            /// This file deals with full projections, transforming all possible types of the union at once.
            /// For partial transforming, see the other part of this partial class.
            /// </remarks>
            public static partial class ProjectExtensions
            {{{string.Join("\n", arities.Select(GenerateProjections))}}
            }
            """;
    }

    private static string GenerateProjections(int arity)
    {
        var arities = Enumerable.Range(1, arity).ToArray();
        var genericArgs = $"<{string.Join(", ", arities.Select(i => $"T{i}"))}>";
        var newArgs = $"<{string.Join(", ", arities.Select(i => $"TNew{i}"))}>";

        return $$"""

                     #region Projection Extensions for Union{{genericArgs}}

                     extension{{genericArgs}}(Union{{genericArgs}} union)
                     {
                 {{Project(arities, newArgs)}}
                 {{ProjectAsync(arities, newArgs)}}
                     }
                     
                     extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                     {
                 {{TaskProject(arities, newArgs)}}    
                 {{TaskProjectAsync(arities, newArgs)}}
                     }

                     #endregion
                 """;
    }

    private static string Project(int[] arities, string newArgs)
    {
        return $$"""
                        /// <summary>
                        /// Apply projecting functions to the value stored in the union based on its current state.
                        /// </summary>
                        {{string.Join("\n       ", arities.Select(i => $"/// <param name=\"projectT{i}\">The projection function if the union is in the T{i} state. </param>"))}}
                        public Union{{newArgs}} Project{{newArgs}}({{string.Join(", ", arities.Select(i => $"Func<T{i},TNew{i}> projectT{i}"))}})
                        {
                            {{string.Join("\n           ", arities.Select(i => $"ArgumentNullException.ThrowIfNull(projectT{i});"))}}
                            
                            return union.Match(
                               {{string.Join(",\n              ", arities.Select(i => MatchLine(i, newArgs)))}}
                            );
                        }
                 """;
    }

    private static string ProjectAsync(int[] arities, string newArgs)
    {
        return $$"""
                 
                        /// <summary>
                        /// Apply async projecting functions to the value stored in the union based on its current state.
                        /// </summary>
                        {{string.Join("\n       ", arities.Select(i => $"/// <param name=\"projectT{i}Async\">The async projection function if the union is in the T{i} state. </param>"))}}
                        public Task<Union{{newArgs}}> ProjectAsync{{newArgs}}({{string.Join(", ", arities.Select(i => $"Func<T{i}, Task<TNew{i}>> projectT{i}Async"))}})
                        {
                            {{string.Join("\n           ", arities.Select(i => $"ArgumentNullException.ThrowIfNull(projectT{i}Async);"))}}
                            
                            return union.MatchAsync(
                               {{string.Join(",\n              ", arities.Select(i => MatchLineAsync(i, newArgs)))}}
                            );
                        }
                 """;
    }

    private static string TaskProject(int[] arities, string newArgs)
    {
        return $$"""
                 
                        /// <summary>
                        /// Apply projection functions to the value stored in the task union based on its current state.
                        /// </summary>
                        {{string.Join("\n       ", arities.Select(i => $"/// <param name=\"projectT{i}\">The projection function if the union is in the T{i} state. </param>"))}}
                        public async Task<Union{{newArgs}}> Project{{newArgs}}({{string.Join(", ", arities.Select(i => $"Func<T{i},TNew{i}> projectT{i}"))}})
                        {
                            var union = await unionTask.ConfigureAwait(false);
                            return union.Project({{string.Join(", ", arities.Select(i => $"projectT{i}"))}});
                        }        
                 """;
    }

    private static string TaskProjectAsync(int[] arities, string newArgs)
    {
        return $$"""

                        /// <summary>
                        /// Apply async projection functions to the value stored in the task union based on its current state.
                        /// </summary>
                        {{string.Join("\n       ", arities.Select(i => $"/// <param name=\"projectT{i}Async\">The async projection function if the union is in the T{i} state. </param>"))}}
                        public async Task<Union{{newArgs}}> ProjectAsync{{newArgs}}({{string.Join(", ", arities.Select(i => $"Func<T{i}, Task<TNew{i}>> projectT{i}Async"))}})
                        {
                            var union = await unionTask.ConfigureAwait(false);
                            return await union.ProjectAsync({{string.Join(", ", arities.Select(i => $"projectT{i}Async"))}}).ConfigureAwait(false);
                        }
                 """;
    }

    private static string MatchLine(int arity, string newArgs)
    {
        return $"t{arity} => Union{newArgs}.FromT{arity}(projectT{arity}(t{arity}))";
    }

    private static string MatchLineAsync(int arity, string newArgs)
    {
        return $"async t{arity} => Union{newArgs}.FromT{arity}(await projectT{arity}Async(t{arity}).ConfigureAwait(false))";
    }
}
