using System.Collections.Immutable;
using System.Text;
using Toarnbeike.Unions.SourceGenerator.Model;

namespace Toarnbeike.Unions.SourceGenerator.Generators;

internal static class CoreGenerator
{
    public static string Execute(UnionModel model)
    {
        return $$"""
                # nullable enable

                // <auto-generated>
                //   This file was generated by Toarnbeike.Unions.SourceGenerator.
                //   Generator: {{nameof(CoreGenerator)}}
                //   Created: {{DateTime.UtcNow:u}}
                //   This is an auto-generated file. Do not modify.
                // </auto-generated>
                
                using System.Diagnostics;
                using System.Diagnostics.CodeAnalysis;
                using Toarnbeike.Unions.Generic;
                {{model.CaseUsings}}

                namespace {{model.Namespace}};

                partial class {{model.Name}}
                {
                    private readonly {{model.BackingUnionType}} {{model.BackingFieldName}};

                    private {{model.Name}}({{model.BackingUnionType}} value)
                    {
                        {{model.BackingFieldName}} = value;
                    }

                {{GenerateConstructors(model)}}
                {{GenerateIsProperties(model.Cases)}}
                {{GenerateTryGetMethods(model.Cases)}}

                    internal {{model.BackingUnionType}} AsUnion() => {{model.BackingFieldName}};

                    internal static {{model.Name}} FromUnion({{model.BackingUnionType}} union) => new(union);

                    internal static async Task<{{model.Name}}> FromUnionAsync(Task<{{model.BackingUnionType}}> unionTask) => new(await unionTask);

                    public static implicit operator {{model.Name}}({{model.BackingUnionType}} union) => FromUnion(union);
                }
                """;
    }
    

    private static string GenerateConstructors(UnionModel model)
    {
        var sb = new StringBuilder();

        foreach (var caseModel in model.Cases)
        {
            sb.AppendLine($$"""

                 /// <summary>
                 /// Creates a new union instance by providing the {{caseModel.Name}} to store in it.
                 /// </summary>
                 /// <param name="value">The {{caseModel.Name}}} to store in the union.</param>
                 public static {{model.Name}} {{caseModel.Name}}({{caseModel.TypeName}} value)
                     => new({{model.BackingUnionType}}.FromT{{caseModel.Index}}(value));
             """);
        }

        return sb.ToString();
    }

    private static string GenerateIsProperties(ImmutableArray<UnionCaseModel> caseModels)
    {
        var sb = new StringBuilder();

        foreach (var caseModel in caseModels)
        {
            sb.AppendLine($$"""

                 /// <summary>
                 /// Indicates whether the union is in {{caseModel.Name}} state.
                 /// </summary>
                 public bool Is{{caseModel.Name}} => _value.IsT{{caseModel.Index}};
             """);
        }

        return sb.ToString();
    }

    private static string GenerateTryGetMethods(ImmutableArray<UnionCaseModel> caseModels)
    {
        var sb = new StringBuilder();
        foreach (var caseModel in caseModels)
        {
            sb.AppendLine($$"""

                 /// <summary>
                 /// Attempts to get the stored {{caseModel.Name}} value from the union.
                 /// </summary>
                 /// <param name="value">When this method returns, contains the {{caseModel.Name}} value if the union is in that state; otherwise, the default value for {{caseModel.TypeName}}.</param>
                 /// <returns>true if the union is in {{caseModel.Name}} state; otherwise, false.</returns>
                 public bool TryGet{{caseModel.Name}}([MaybeNullWhen(false)] out {{caseModel.TypeName}} value) => 
                    _value.TryGetT{{caseModel.Index}}(out value);
             """);
        }
        return sb.ToString();
    }
}
