using Toarnbeike.Unions.SourceGenerator.Model;

#pragma warning disable CS0162 // Unreachable code detected - Mapping of all branches at once is for now disabled, could later be reinstated.
// ReSharper disable HeuristicUnreachableCode

namespace Toarnbeike.Unions.SourceGenerator.Generators;

internal static class MapGenerator
{
    public static string Execute(UnionModel model)
    {
        return $$"""
            # nullable enable
            
            // <auto-generated>
            //   This file was generated by Toarnbeike.Unions.SourceGenerator.
            //   Generator: {{nameof(MapGenerator)}}
            //   Created: {{DateTime.UtcNow:u}}
            //   This is an auto-generated file. Do not modify.
            // </auto-generated>
            
            using Toarnbeike.Unions.Generic;
            using Toarnbeike.Unions.Generic.Extensions;
            {{model.CaseUsings}}
            
            namespace {{model.Namespace}};

            /// <summary>
            /// Map: extension methods to map union values, modifying the inner value, but keeping the types equal (endomorphic).
            /// </summary>
            public static class {{model.Name}}MapExtensions
            {
                extension({{model.Name}} {{model.ArgumentName}})
                {
            {{GenerateMapExtension(model)}}
            {{string.Join("\n", model.Cases.Select(unionCase => GenerateMapTExtension(model, unionCase)))}}
            {{GenerateMapAsyncExtension(model)}}
            {{string.Join("\n", model.Cases.Select(unionCase => GenerateMapTAsyncExtension(model, unionCase)))}}
                }
                extension(Task<{{model.Name}}> {{model.ArgumentName}}Task)
                {
            {{GenerateTaskMapExtension(model)}}
            {{string.Join("\n", model.Cases.Select(unionCase => GenerateTaskMapTExtension(model, unionCase)))}}
            {{GenerateTaskMapAsyncExtension(model)}}
            {{string.Join("\n", model.Cases.Select(unionCase => GenerateTaskMapTAsyncExtension(model, unionCase)))}}
                }
            }
            """;
    }

    private static string GenerateMapExtension(UnionModel model)
    {
        return string.Empty;
        var parameters = string.Join(", ", model.Cases.Select(c =>
            $"Func<{c.TypeName}, {c.TypeName}> map{c.Name}"));

        var xmlParameters = string.Join("\n        ", model.Cases.Select(c =>
            $"/// <param name=\"map{c.Name}\">The mapping function if the union is in the {c.Name} value state. </param>"));

        var arguments = string.Join(", ", model.Cases.Select(c => $"map{c.Name}"));

        return $"""
                    /// <summary>
                    /// Apply mapping functions to the value stored in the union based on its current state.
                    /// </summary>
                    {xmlParameters}
                    public {model.Name} Map({parameters}) =>
                        {model.Name}.FromUnion({model.ArgumentName}.AsUnion().Map({arguments}));

            """;

    }
    
    private static string GenerateMapTExtension(UnionModel model, UnionCaseModel caseModel)
    {
        return $"""
                    /// <summary>
                    /// Apply a mapping function to the value stored in the union if it is in the {caseModel.Name} state.
                    /// </summary>
                    /// <param name="map">The mapping function to apply.</param>
                    public {model.Name} Map{caseModel.Name}(Func<{caseModel.TypeName}, {caseModel.TypeName}> map) =>
                        {model.Name}.FromUnion({model.ArgumentName}.AsUnion().Map{caseModel.BackingTypeName}(map));

            """;
    }

    private static string GenerateMapAsyncExtension(UnionModel model)
    {
        return string.Empty;
        var parameters = string.Join(", ", model.Cases.Select(c =>
            $"Func<{c.TypeName}, Task<{c.TypeName}>> map{c.Name}Async"));

        var xmlParameters = string.Join("\n        ", model.Cases.Select(c =>
            $"/// <param name=\"map{c.Name}Async\">The async mapping function if the union is in the {c.Name} value state. </param>"));

        var arguments = string.Join(", ", model.Cases.Select(c => $"map{c.Name}Async"));

        return $"""
                    /// <summary>
                    /// Apply async mapping functions to the value stored in the union bases on its current state.
                    /// </summary>
                    {xmlParameters}
                    public async Task<{model.Name}> MapAsync({parameters}) =>
                        await {model.Name}.FromUnionAsync({model.ArgumentName}.AsUnion().MapAsync({arguments}));

            """;
    }

    private static string GenerateMapTAsyncExtension(UnionModel model, UnionCaseModel caseModel)
    {
        return $"""
                    /// <summary>
                    /// Apply an async mapping function to the value stored in the union if it is in the {caseModel.Name} state.
                    /// </summary>
                    /// <param name="mapAsync">The async mapping function to apply.</param>
                    public async Task<{model.Name}> Map{caseModel.Name}Async(Func<{caseModel.TypeName}, Task<{caseModel.TypeName}>> mapAsync) =>
                        await {model.Name}.FromUnionAsync({model.ArgumentName}.AsUnion().Map{caseModel.BackingTypeName}Async(mapAsync));
            
            """;
    }

    private static string GenerateTaskMapExtension(UnionModel model)
    {
        return string.Empty;
        var parameters = string.Join(", ", model.Cases.Select(c =>
            $"Func<{c.TypeName}, {c.TypeName}> map{c.Name}"));

        var xmlParameters = string.Join("\n        ", model.Cases.Select(c =>
            $"/// <param name=\"map{c.Name}\">The mapping function if the union is in the {c.Name} value state. </param>"));

        var arguments = string.Join(", ", model.Cases.Select(c => $"map{c.Name}"));

        return $$"""
                    /// <summary>
                    /// Apply mapping functions to the value stored in the union Task based on its current state.
                    /// </summary>
                    {{xmlParameters}}
                    public async Task<{{model.Name}}> Map({{parameters}})
                    {
                        var {{model.ArgumentName}} = await {{model.ArgumentName}}Task;
                        return {{model.ArgumentName}}.Map({{arguments}});
                    }

            """;

    }

    private static string GenerateTaskMapTExtension(UnionModel model, UnionCaseModel caseModel)
    {
        return $$"""
                    /// <summary>
                    /// Apply a mapping function to the value stored in the union Task if it is in the {{caseModel.Name}} state.
                    /// </summary>
                    /// <param name="map">The mapping function to apply.</param>
                    public async Task<{{model.Name}}> Map{{caseModel.Name}}(Func<{{caseModel.TypeName}}, {{caseModel.TypeName}}> map)
                    {
                        var {{model.ArgumentName}} = await {{model.ArgumentName}}Task;
                        return {{model.ArgumentName}}.Map{{caseModel.Name}}(map);
                    }

            """;
    }

    private static string GenerateTaskMapAsyncExtension(UnionModel model)
    {
        return string.Empty;
        var parameters = string.Join(", ", model.Cases.Select(c =>
            $"Func<{c.TypeName}, Task<{c.TypeName}>> map{c.Name}Async"));

        var xmlParameters = string.Join("\n        ", model.Cases.Select(c =>
            $"/// <param name=\"map{c.Name}Async\">The async mapping function if the union is in the {c.Name} value state. </param>"));

        var arguments = string.Join(", ", model.Cases.Select(c => $"map{c.Name}Async"));

        return $$"""
                    /// <summary>
                    /// Apply async mapping functions to the value stored in the union Task bases on its current state.
                    /// </summary>
                    {{xmlParameters}}
                    public async Task<{{model.Name}}> MapAsync({{parameters}})
                    {
                        var {{model.ArgumentName}} = await {{model.ArgumentName}}Task;
                        return await {{model.ArgumentName}}.MapAsync({{arguments}});
                    }

            """;
    }

    private static string GenerateTaskMapTAsyncExtension(UnionModel model, UnionCaseModel caseModel)
    {
        return $$"""
                    /// <summary>
                    /// Apply an async mapping function to the value stored in the union Task if it is in the {{caseModel.Name}} state.
                    /// </summary>
                    /// <param name="mapAsync">The async mapping function to apply.</param>
                    public async Task<{{model.Name}}> Map{{caseModel.Name}}Async(Func<{{caseModel.TypeName}}, Task<{{caseModel.TypeName}}>> mapAsync)
                    {
                        var {{model.ArgumentName}} = await {{model.ArgumentName}}Task;
                        return await {{model.ArgumentName}}.Map{{caseModel.Name}}Async(mapAsync);
                    }
            
            """;
    }
}