using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// Generates the Union.SelectT and Union.Partition extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class CollectionExtensionsWriter
{
    public static string WriteFile(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(CollectionExtensionsWriter).FullName!)}}

            using Toarnbeike.Unions.Generic.Extensions;

            namespace Toarnbeike.Unions.Generic.Collections;

            /// <summary>
            /// Collections: extension methods to collections of unions. Select a given type or partition the collection into collections of their constituent types.
            /// </summary>
            public static class CollectionExtensions
            {
            {{arities.Select(GeneratePartition).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string GeneratePartition(int arity)
    {
        var arityList = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{arityList.Select(i => $"T{i}").JoinCommaSeparated()}>";

        return $$"""
                 #region Collection Extensions for Union{{genericArgs}}
                 
                 /// <param name="source">The source collection of unions.</param>
                 extension{{genericArgs}}(IEnumerable<Union{{genericArgs}}> source)
                 {
                 {{arityList.Select(SelectT).JoinParagraphs().Indent(1)}}

                 {{Partition(arityList).Indent(1)}}
                 }

                 #endregion
                 """;
    }

    private static string Partition(List<int> arityList)
    {
        return $$"""
                 /// <summary>
                 /// Partitions a collection of unions into separate collections for each type in the union.
                 /// </summary>
                 /// <returns>A tuple containing a list for each type in the union.</returns>
                 public ({{arityList.Select(i => $"IReadOnlyList<T{i}> T{i}s").JoinCommaSeparated()}}) Partition()
                 {
                     ArgumentNullException.ThrowIfNull(source);

                 {{arityList.Select(i => $"var t{i}Set = new List<T{i}>();").JoinLines().Indent(1)}}

                     foreach (var union in source)
                     {
                         union.Switch({{arityList.Select(i => $"t{i}Set.Add").JoinCommaSeparated()}});
                     }

                     return ({{arityList.Select(i => $"t{i}Set").JoinCommaSeparated()}});
                 }
                 """;
    }

    private static string SelectT(int arity)
    {
        return $$"""
                  /// <summary>
                  /// Select all elements of type T{{arity}} from the collection of unions.
                  /// </summary>
                  public IEnumerable<T{{arity}}> SelectT{{arity}}()
                  {
                      ArgumentNullException.ThrowIfNull(source);

                      return source.Where(union => union.IsT{{arity}}).Select(union => union.AsT{{arity}});
                  }
                  """;
    }
}
