using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// Generates the union.Map extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
/// <remarks> The MapTExtensions are generated in <see cref="MapPartialExtensionsWriter"/></remarks>
internal static class MapFullExtensionsWriter
{
    public static string WriteFile(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(MapFullExtensionsWriter).FullName!)}}
            
            namespace Toarnbeike.Unions.Generic.Extensions;

            /// <summary>
            /// Map: extension methods to map (transform) union values.
            /// </summary>
            /// <remarks> 
            /// This file deals with full mappings, transforming all possible types of the union at once.
            /// For partial transforming, see the other part of this partial class.
            /// </remarks>
            public static partial class MapExtensions
            {
            {{arities.Select(GenerateMaps).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string GenerateMaps(int arity)
    {
        var arities = Enumerable.Range(1, arity).ToArray();
        var genericArgs = $"<{arities.Select(i => $"T{i}").JoinCommaSeparated()}>";
        var newArgs = $"<{arities.Select(i => $"TNew{i}").JoinCommaSeparated()}>";

        return $$"""
                 #region Map Extensions for Union{{genericArgs}}
                 
                 extension{{genericArgs}}(Union{{genericArgs}} union)
                 {
                 {{Map(arities, newArgs).Indent(1)}}
                 
                 {{MapAsync(arities, newArgs).Indent(1)}}
                 }
                     
                 extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                 {
                 {{TaskMap(arities, newArgs).Indent(1)}}
                 
                 {{TaskMapAsync(arities, newArgs).Indent(1)}}
                 }
                 
                 #endregion
                 """;
    }

    private static string Map(int[] arities, string newArgs)
    {
        return $$"""
                 /// <summary>
                 /// Apply mapping functions to the value stored in the union based on its current state.
                 /// </summary>
                 {{arities.Select(i => $"/// <param name=\"mapT{i}\">The mapping function if the union is in the T{i} state. </param>").JoinLines()}}
                 public Union{{newArgs}} Map{{newArgs}}({{arities.Select(i => $"Func<T{i},TNew{i}> mapT{i}").JoinCommaSeparated()}})
                 {
                 {{arities.Select(i => $"ArgumentNullException.ThrowIfNull(mapT{i});").JoinLines().Indent(1)}}
                     
                     return union.Match(
                 {{arities.Select(i => MatchLine(i, newArgs)).JoinCommaSeparatedLines().Indent(2)}}
                     );
                 }
                 """;
    }

    private static string MapAsync(int[] arities, string newArgs)
    {
        return $$"""
                 /// <summary>
                 /// Apply async mapping functions to the value stored in the union based on its current state.
                 /// </summary>
                 {{arities.Select(i => $"/// <param name=\"mapT{i}Async\">The async mapping function if the union is in the T{i} state. </param>").JoinLines()}}
                 public Task<Union{{newArgs}}> MapAsync{{newArgs}}({{arities.Select(i => $"Func<T{i}, Task<TNew{i}>> mapT{i}Async").JoinCommaSeparated()}})
                 {
                 {{arities.Select(i => $"ArgumentNullException.ThrowIfNull(mapT{i}Async);").JoinLines().Indent(1)}}
                     
                     return union.MatchAsync(
                 {{arities.Select(i => MatchLineAsync(i, newArgs)).JoinCommaSeparatedLines().Indent(2)}}
                     );
                 }
                 """;
    }

    private static string TaskMap(int[] arities, string newArgs)
    {
        return $$"""
                 /// <summary>
                 /// Apply mapping functions to the value stored in the task union based on its current state.
                 /// </summary>
                 {{arities.Select(i => $"/// <param name=\"mapT{i}\">The mapping function if the union is in the T{i} state. </param>").JoinLines()}}
                 public async Task<Union{{newArgs}}> Map{{newArgs}}({{arities.Select(i => $"Func<T{i},TNew{i}> mapT{i}").JoinCommaSeparated()}})
                 {
                     var union = await unionTask.ConfigureAwait(false);
                     return union.Map({{arities.Select(i => $"mapT{i}").JoinCommaSeparated()}});
                 }        
                 """;
    }

    private static string TaskMapAsync(int[] arities, string newArgs)
    {
        return $$"""
                 /// <summary>
                 /// Apply async mapping functions to the value stored in the task union based on its current state.
                 /// </summary>
                 {{arities.Select(i => $"/// <param name=\"mapT{i}Async\">The async mapping function if the union is in the T{i} state. </param>").JoinLines()}}
                 public async Task<Union{{newArgs}}> MapAsync{{newArgs}}({{arities.Select(i => $"Func<T{i}, Task<TNew{i}>> mapT{i}Async").JoinCommaSeparated()}})
                 {
                     var union = await unionTask.ConfigureAwait(false);
                     return await union.MapAsync({{arities.Select(i => $"mapT{i}Async").JoinCommaSeparated()}}).ConfigureAwait(false);
                 }
                 """;
    }

    private static string MatchLine(int arity, string newArgs)
    {
        return $"t{arity} => Union{newArgs}.FromT{arity}(mapT{arity}(t{arity}))";
    }

    private static string MatchLineAsync(int arity, string newArgs)
    {
        return $"async t{arity} => Union{newArgs}.FromT{arity}(await mapT{arity}Async(t{arity}).ConfigureAwait(false))";
    }
}
