using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// Generates the union.Match extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class MatchExtensionsWriter
{
    public static string WriteFile(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(MatchExtensionsWriter).FullName!)}}
            
            namespace Toarnbeike.Unions.Generic.Extensions;

            /// <summary>
            /// Match: extension methods to match (fold; convert to result) union values.
            /// </summary>
            public static class MatchExtensions
            {
            {{arities.Select(GenerateMatch).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string GenerateMatch(int arity)
    {
        var collection = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{collection.Select(i => $"T{i}").JoinCommaSeparated()}>";

        return $$"""
                 #region Match Extensions for Union{{genericArgs}}

                 extension{{genericArgs}}(Union{{genericArgs}} union)
                 {
                     /// <summary>
                     /// Matches the value stored in the union and invokes the corresponding function based on its type.
                     /// </summary>
                     /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                 {{collection.Select(i => ParamXmlComments(i, false)).JoinLines().Indent(1)}}
                     /// <returns>The result of invoking the appropriate match function.</returns>
                     /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                     public TResult Match<TResult>({{collection.Select(i => $"Func<T{i}, TResult> onT{i}").JoinCommaSeparated()}})
                     {
                 {{collection.Select(i => $"ArgumentNullException.ThrowIfNull(onT{i});").JoinLines().Indent(2)}}
             
                         return union.Index switch
                         {
                 {{collection.Select(i => SwitchLine(i, false)).JoinLines().Indent(3)}}
                            _ => throw new InvalidOperationException($"Union index {union.Index} is invalid.")
                         };
                     }
                     
                     /// <summary>
                     /// Matches the value stored in the union and invokes the corresponding async function based on its type.
                     /// </summary>
                     /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                 {{collection.Select(i => ParamXmlComments(i, true)).JoinLines().Indent(1)}}
                     /// <returns>The result of invoking the appropriate match function.</returns>
                     /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                     public Task<TResult> MatchAsync<TResult>({{collection.Select(i => $"Func<T{i}, Task<TResult>> onT{i}Async").JoinCommaSeparated()}})
                     {
                 {{collection.Select(i => $"ArgumentNullException.ThrowIfNull(onT{i}Async);").JoinLines().Indent(2)}}
             
                         return union.Index switch
                         {
                 {{collection.Select(i => SwitchLine(i, true)).JoinLines().Indent(3)}}
                            _ => Task.FromException<TResult>(new InvalidOperationException($"Union index {union.Index} is invalid."))
                         };
                     }
                 }
                 
                 extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                 {
                     /// <summary>
                     /// Matches the value stored in the union and invokes the corresponding function based on its type.
                     /// </summary>
                     /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                 {{collection.Select(i => ParamXmlComments(i, false)).JoinLines().Indent(1)}}
                     /// <returns>The result of invoking the appropriate match function.</returns>
                     /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                     public async Task<TResult> Match<TResult>({{collection.Select(i => $"Func<T{i}, TResult> onT{i}").JoinCommaSeparated()}})
                     {
                         var union = await unionTask.ConfigureAwait(false);
                         return union.Match({{collection.Select(i => $"onT{i}").JoinCommaSeparated()}});
                    }
                     
                     /// <summary>
                     /// Matches the value stored in the union and invokes the corresponding async function based on its type.
                     /// </summary>
                     /// <typeparam name="TResult">The type of the result returned by the match functions.</typeparam>
                 {{collection.Select(i => ParamXmlComments(i, true)).JoinLines().Indent(1)}}
                     /// <returns>The result of invoking the appropriate match function.</returns>
                     /// <exception cref="InvalidOperationException">Thrown if the union is not in a valid state.</exception>
                     public async Task<TResult> MatchAsync<TResult>({{collection.Select(i => $"Func<T{i}, Task<TResult>> onT{i}Async").JoinCommaSeparated()}})
                     {
                         var union = await unionTask.ConfigureAwait(false);
                         return await union.MatchAsync({{collection.Select(i => $"onT{i}Async").JoinCommaSeparated()}}).ConfigureAwait(false);
                     }
                 }

                 #endregion
                 """;
    }

    private static string ParamXmlComments(int arity, bool async)
    {
        var asyncSuffix = async ? "Async" : "";
        var asyncComment = async ? "async " : "";
        return $"/// <param name=\"onT{arity}{asyncSuffix}\">The {asyncComment}function to invoke when the union holds a value of type T{arity}.</param>";
    }

    private static string SwitchLine(int arity, bool async)
    {
        return $"{arity} => onT{arity}{(async ? "Async" : "")}(union.AsT{arity}),";
    }
}
