using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// Generates the Union.Switch extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class SwitchExtensionsWriter
{
    public static string WriteFile(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(SwitchExtensionsWriter).FullName!)}}

            namespace Toarnbeike.Unions.Generic.Extensions;

            /// <summary>
            /// Switch: extension methods to perform an action on union values.
            /// </summary>
            public static class SwitchExtensions
            {
            {{arities.Select(GenerateSwitch).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string GenerateSwitch(int arity)
    {
        var collection = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{collection.Select(i => $"T{i}").JoinCommaSeparated()}>";

        return $$"""
                 #region Switch Extensions for Union{{genericArgs}}

                 extension{{genericArgs}}(Union{{genericArgs}} union)
                 {
                     /// <summary>
                     /// Switch on the value stored in the union and invokes the corresponding side effect based on its type.
                     /// </summary>
                 {{collection.Select(i => ParamXmlComments(i, false)).JoinLines().Indent(1)}}
                     public void Switch({{collection.Select(i => $"Action<T{i}> onT{i}").JoinCommaSeparated()}})
                     {
                 {{collection.Select(i => $"ArgumentNullException.ThrowIfNull(onT{i});").JoinLines().Indent(2)}}
                 
                         switch (union.Index)
                         {
                 {{collection.Select(i => SwitchLine(i, false)).JoinLines().Indent(3)}}
                             default: throw new InvalidOperationException($"Union index {union.Index} is invalid for Union{{genericArgs}}.");
                         }
                     }
                     
                     /// <summary>
                     /// Switch on the value stored in the union and invokes the corresponding async side effect based on its type.
                     /// </summary>
                 {{collection.Select(i => ParamXmlComments(i, true)).JoinLines().Indent(1)}}
                     public async Task SwitchAsync({{collection.Select(i => $"Func<T{i}, Task> onT{i}Async").JoinCommaSeparated()}})
                     {
                 {{collection.Select(i => $"ArgumentNullException.ThrowIfNull(onT{i}Async);").JoinLines().Indent(2)}}
                 
                         switch (union.Index)
                         {
                 {{collection.Select(i => SwitchLine(i, true)).JoinLines().Indent(3)}}
                             default: throw new InvalidOperationException($"Union index {union.Index} is invalid for Union{{genericArgs}}.");
                         }
                     }
                 }
                 
                 extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                 {
                     /// <summary>
                     /// Switch on the value stored in the union and invokes the corresponding side effect based on its type.
                     /// </summary>
                 {{collection.Select(i => ParamXmlComments(i, false)).JoinLines().Indent(1)}}
                     public async Task Switch({{collection.Select(i => $"Action<T{i}> onT{i}").JoinCommaSeparated()}})
                     {
                         var union = await unionTask.ConfigureAwait(false);
                         union.Switch({{collection.Select(i => $"onT{i}").JoinCommaSeparated()}});
                     }
                     
                     /// <summary>
                     /// Switch on the value stored in the union and invokes the corresponding async side effect based on its type.
                     /// </summary>
                 {{collection.Select(i => ParamXmlComments(i, true)).JoinLines().Indent(1)}}
                     public async Task SwitchAsync({{collection.Select(i => $"Func<T{i}, Task> onT{i}Async").JoinCommaSeparated()}})
                     {
                         var union = await unionTask.ConfigureAwait(false);
                         await union.SwitchAsync({{collection.Select(i => $"onT{i}Async").JoinCommaSeparated()}});
                     }
                 }

                 #endregion
                 """;
    }

    private static string ParamXmlComments(int arity, bool async)
    {
        var asyncSuffix = async ? "Async" : "";
        var asyncComment = async ? "async " : "";
        return
            $"/// <param name=\"onT{arity}{asyncSuffix}\">The {asyncComment}action to invoke when the union holds a value of type T{arity}.</param>";
    }

    private static string SwitchLine(int arity, bool async)
    {
        return async ?
            $"case {arity}: await onT{arity}Async(union.AsT{arity}).ConfigureAwait(false); break;" :
            $"case {arity}: onT{arity}(union.AsT{arity}); break;";
    }
}