using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// Generates the union.Tap extension methods for the requested arities.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class TapExtensionsWriter
{
    public static string WriteFile(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(TapExtensionsWriter).FullName!)}}

            namespace Toarnbeike.Unions.Generic.Extensions;

            /// <summary>
            /// Tap: extension methods to apply a side effect when the union is in a given state.
            /// Returns the original union for fluent chaining.
            /// </summary>
            public static class TapExtensions
            {
            {{arities.Select(GenerateTap).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string GenerateTap(int arity)
    {
        var arities = Enumerable.Range(1, arity).ToArray();
        var genericArgs = $"<{arities.Select(i => $"T{i}").JoinCommaSeparated()}>";
        return $$"""
                 #region Tap Extensions for Union{{genericArgs}}

                 extension{{genericArgs}}(Union{{genericArgs}} union)
                 {
                 {{arities.Select(i => Tap(i, genericArgs)).JoinLines().Indent(1)}}
                 
                 {{arities.Select(i => TapAsync(i, genericArgs)).JoinLines().Indent(1)}}
                 }
                     
                 extension{{genericArgs}}(Task<Union{{genericArgs}}> unionTask)
                 {
                 {{arities.Select(i => TaskTap(i, genericArgs)).JoinLines().Indent(1)}}
                 
                 {{arities.Select(i => TaskTapAsync(i, genericArgs)).JoinLines().Indent(1)}}
                 }

                 #endregion
                 """;
    }

    private static string Tap(int arity, string genericArgs)
    {
        return $$"""
                 /// <summary>
                 /// Handle a side effect function to the value stored in the union if it is in the T{{arity}} state.
                 /// </summary>
                 /// <param name="handle">The side effect to handle.</param>
                 public Union{{genericArgs}} TapT{{arity}}(Action<T{{arity}}> handle)
                 {
                     ArgumentNullException.ThrowIfNull(handle);

                     if (union.TryGetT{{arity}}(out var value))
                     {
                         handle(value);
                     }
                     return union;
                 }
                 """;
    }

    private static string TapAsync(int arity, string genericArgs)
    {
        return $$"""
                 /// <summary>
                 /// Handle an async side effect function to the value stored in the union if it is in the T{{arity}} state.
                 /// </summary>
                 /// <param name="handleAsync">The async side effect to handle.</param>
                 public async Task<Union{{genericArgs}}> TapT{{arity}}Async(Func<T{{arity}}, Task> handleAsync)
                 {
                     ArgumentNullException.ThrowIfNull(handleAsync);

                     if (union.TryGetT{{arity}}(out var value))
                     {
                         await handleAsync(value).ConfigureAwait(false);
                     }
                     return union;
                 }
                 """;
    }

    private static string TaskTap(int arity, string genericArgs)
    {
        return $$"""
                 /// <summary>
                 /// Handle a side effect function to the value stored in the task union if it is in the T{{arity}} state.
                 /// </summary>
                 /// <param name="handle">The side effect to handle.</param>
                 public async Task<Union{{genericArgs}}> TapT{{arity}}(Action<T{{arity}}> handle)
                 {
                     var union = await unionTask.ConfigureAwait(false);
                     return union.TapT{{arity}}(handle);
                 }
                 """;
    }

    private static string TaskTapAsync(int arity, string genericArgs)
    {
        return $$"""
                 /// <summary>
                 /// Handle an async side effect function to the value stored in the task union if it is in the T{{arity}} state.
                 /// </summary>
                 /// <param name="handleAsync">The async side effect to handle.</param>
                 public async Task<Union{{genericArgs}}> TapT{{arity}}Async(Func<T{{arity}}, Task> handleAsync)
                 {
                     var union = await unionTask.ConfigureAwait(false);
                     return await union.TapT{{arity}}Async(handleAsync).ConfigureAwait(false);
                 }
                 """;
    }
}