using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// This generates test extension methods for Union types to facilitate unit testing.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class TestExtensionsWriter
{
    public static string WriteFile(IEnumerable<int> arities)
    {
        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(TestExtensionsWriter).FullName!)}}

            namespace Toarnbeike.Unions.Generic.TestExtensions;

            /// <summary>
            /// Provides extension methods for testing Union types in unit tests.
            /// </summary>
            public static class TestExtensions
            {
            {{arities.Select(GenerateTestExtension).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string GenerateTestExtension(int arity)
    {
        var arityList = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{arityList.Select(i => $"T{i}").JoinCommaSeparated()}>";
        return $$"""
                 #region Test Extensions for Union{{genericArgs}}

                 extension{{genericArgs}}(Union{{genericArgs}} union)
                 {
                 {{arityList.Select(ShouldBeT).JoinParagraphs().Indent(1)}}
                 }

                 #endregion
                 """;
    }

    private static string ShouldBeT(int arity)
    {
        return $$"""
                 /// <summary>
                 /// Verifies that the union is in the T{{arity}} state.
                 /// </summary>
                 /// <returns>The value of the union, as T{{arity}}, if the union is in the T{{arity}} state.</returns>
                 /// <exception cref="AssertionFailedException">Thrown if the union is not in the T{{arity}} state.</exception>
                 public T{{arity}} ShouldBeT{{arity}}()
                 {
                     if (union.Index == 0)
                     {
                         throw new AssertionFailedException("Union is in the uninitialized (default) state.");
                     }

                     return union.IsT{{arity}} 
                         ? union.AsT{{arity}} 
                         : throw new AssertionFailedException($"Expected union to be T{{arity}}, but it was T{union.Index} ({union.DebuggerToString()}).");
                 }
                 """;
    }
}
