using WriterLibrary;

namespace UnionWriters.Writers;

/// <summary>
/// Generates the core Union{T1…Tn} types.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class UnionWriter
{
    public static string WriteFile(int[] arities)
    {
        return $"""
            {AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(UnionWriter).FullName!)}

            using System.Diagnostics;
            using System.Diagnostics.CodeAnalysis;

            namespace Toarnbeike.Unions.Generic;
            
            {arities.Select(GenerateUnion).JoinParagraphs().Indent(1)}
            """;
    }

    private static string GenerateUnion(int arity)
    {
        var collection = Enumerable.Range(1, arity).ToList();
        var genericArgs = $"<{collection.Select(i => $"T{i}").JoinCommaSeparated()}>";

        return $$"""
                 #region Union{{genericArgs}}

                 /// <summary>
                 /// Union type with {{arity}} variants.
                 /// </summary>
                 [DebuggerDisplay("{DebuggerToString(),nq}")]
                 public readonly record struct Union{{genericArgs}}
                 {
                     /// <summary>
                     /// The value stored in the union.
                     /// </summary>
                     private readonly object _value;
                     
                     /// <summary>
                     /// The index of the variant stored in the union.
                     /// </summary>
                     internal byte Index { get; }
                     
                 {{collection.Select(i => StaticFactory(i, genericArgs)).JoinParagraphs().Indent(1)}}
                 
                 {{collection.Select(IsProperty).JoinParagraphs().Indent(1)}}
                 
                 {{collection.Select(AsProperty).JoinParagraphs().Indent(1)}}
                 
                 {{collection.Select(TryGetMethod).JoinParagraphs().Indent(1)}}
                 
                     private Union(byte index, object? value)
                     {
                         ArgumentNullException.ThrowIfNull(value);

                         (Index, _value) = (index, value);
                     }

                     /// <summary>
                     /// Debugger string representation of the union.
                     /// </summary>
                     internal string DebuggerToString()
                     {
                         return Index switch
                         {
                 {{collection.Select(DebuggerToStringLine).JoinLines().Indent(3)}}
                             _ => "<uninitialized>"
                         };
                     }
                 }
                 #endregion
                 """;
    }

    private static string StaticFactory(int arity, string genericArgs)
    {
        return $"""
                /// <summary>
                /// Creates a new union instance by providing the value to store in it.
                /// </summary>
                /// <param name="value">The value to store in the union.</param>
                public static Union{genericArgs} FromT{arity}(T{arity} value) => new({arity}, value);
                """;
    }

    private static string IsProperty(int arity)
    {
        return $"""
                /// <summary>
                /// Indicates whether the union is in T{arity} state.
                /// </summary>
                public bool IsT{arity} => Index == {arity};
                """;
    }

    private static string AsProperty(int arity)
    {
        return $"""
                /// <summary>
                /// Gets the value of the union if it is in the T{arity} state; otherwise, throws an <see cref="InvalidOperationException"/>.
                /// </summary>
                /// <remarks>
                /// This method is explicitly internal. For external use, either use <see cref="TryGetT{arity}"/>, or the Match or Switch methods.
                /// </remarks>
                /// <exception cref="InvalidOperationException">Thrown if the union is not in the T{arity} state.</exception>
                internal T{arity} AsT{arity} => Index == {arity} ? (T{arity})_value : throw new InvalidOperationException("Union is not in T{arity} state.");
                """;
    }

    private static string TryGetMethod(int arity)
    {
        return $$"""
                /// <summary>
                /// Tries to get the value of the union if it is in the T{{arity}} state.
                /// </summary>
                /// <param name="value">The value stored in the union if it is in the T{{arity}} state; otherwise, null.</param>
                public bool TryGetT{{arity}}([MaybeNullWhen(false)] out T{{arity}} value)
                {
                    var isMatch = Index == {{arity}};
                    value = isMatch ? (T{{arity}})_value : default;
                    return isMatch;
                }
                """;
    }

    private static string DebuggerToStringLine(int arity)
    {
        return $$"""
                {{arity}} => $"T{{arity}} ({typeof(T{{arity}}).Name}) = {_value}",
                """;
    }
}