# nullable enable

// <auto-generated>
//   This file was generated by a tool.
//   Writer: UnionTestWriters.Writers.UnionTestTypeGenerator (v. 2.0.0-alpha.1)
//   Created: 2026-04-21 10:01:16Z
//   These test are auto-generated. Do not modify.
// </auto-generated>

namespace Toarnbeike.Unions.Tests.TestTypes;

/*
 * These records are used as test types.
 * Each U[n] will be used as the generic type argument T[n] in Union tests.
 */

public sealed record U1(int Value);
public sealed record U2(int Value);
public sealed record U3(int Value);
public sealed record U4(int Value);
public sealed record U5(int Value);
public sealed record U6(int Value);
public sealed record U7(int Value);
public sealed record U8(int Value);

/// <summary>
/// Exception that is thrown when an assertion that a given function should not be invoked fails.
/// </summary>
internal sealed class ShouldNotBeCalledException() : Exception("This function should not be called.");