using Toarnbeike.Unions.Utitilies;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates tests for the Map full extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class MapFullExtensionsTestsGenerator
{
    private static int[] _arities = null!;
    private static string _union = null!;

    public static string Generate(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{string.Join(',', _arities.Select(i => "U" + i))}>";

        return $$"""
                 {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(MapFullExtensionsTestsGenerator))}}

                 using Toarnbeike.Unions.Extensions;
                 using Toarnbeike.Unions.TestExtensions;
                 using Toarnbeike.Unions.Tests.Unions.TestTypes;
                 // Resharper disable UnusedParameter.Local

                 namespace Toarnbeike.Unions.Tests.Extensions.Map.Generated;

                 public class Map{{arity:D2}}FullTests
                 {
                 {{string.Join("\n", _arities.Select(FactoryMethod))}}
                 {{HelperMethods()}}
                 {{string.Join("\n", _arities.Select(Map))}}
                 {{string.Join("\n", _arities.Select(MapAsync))}}
                 {{string.Join("\n", _arities.Select(TaskMap))}}
                 {{string.Join("\n", _arities.Select(TaskMapAsync))}}
                 }
                 """;
    }

    private static string FactoryMethod(int arity)
    {
        return $"    private static {_union} MakeT{arity}(int v) => {_union}.FromT{arity}(new U{arity}(v));";
    }

    private static string HelperMethods()
    {
        return $"""

                    private static T ShouldNotBeCalled<T>(T original) => throw new ShouldNotBeCalledException();
                    private static Task<T> ShouldNotBeCalledAsync<T>(T original) => throw new ShouldNotBeCalledException();
                """;
    }

    private static string Map(int arity)
    {
        return $$"""

                     [Test]
                     public void Map_Should_InvokeT{{arity}}Mapper()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         var result = union.Map(
                             {{string.Join(",\n            ", _arities.Select(i => MapLine(i, i == arity)))}}
                         );
                         
                         result.ShouldBeT{{arity}}().Value.ShouldBe({{arity + 10}});
                     }
                     
                     [Test]
                     public void Map_Throws_WhenT{{arity}}_Mapper_ReturnsNull()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         
                         Should.Throw<ArgumentNullException>(() => union.Map(
                             {{string.Join(",\n            ", _arities.Select(i => MapLineNull(i, i == arity)))}}
                         ));
                     }   
                 """;
    }

    private static string MapAsync(int arity)
    {
        return $$"""

                     [Test]
                     public async Task MapAsync_Should_InvokeT{{arity}}Mapper()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         var result = await union.MapAsync(
                             {{string.Join(",\n            ", _arities.Select(i => MapLineAsync(i, i == arity)))}}
                         );
                         
                         result.ShouldBeT{{arity}}().Value.ShouldBe({{arity + 10}});
                     }
                     
                     [Test]
                     public async Task MapAsync_Throws_WhenT{{arity}}_Mapper_ReturnsNull()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         
                         await Should.ThrowAsync<ArgumentNullException>(() => union.MapAsync(
                             {{string.Join(",\n            ", _arities.Select(i => MapLineNullAsync(i, i == arity)))}}
                         ));
                     }   
                 """;
    }

    private static string TaskMap(int arity)
    {
        return $$"""

                     [Test]
                     public async Task TaskMap_Should_InvokeT{{arity}}Mapper()
                     {
                         var task = Task.FromResult(MakeT{{arity}}({{arity}}));
                         
                         var result = await task.Map(
                             {{string.Join(",\n            ", _arities.Select(i => MapLine(i, i == arity)))}}
                         );
                         
                         result.ShouldBeT{{arity}}().Value.ShouldBe({{arity + 10}});
                     }
                 """;
    }

    private static string TaskMapAsync(int arity)
    {
        return $$"""

                     [Test]
                     public async Task TaskMapAsync_Should_InvokeT{{arity}}Mapper()
                     {
                         var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                         var result = await task.MapAsync(
                             {{string.Join(",\n            ", _arities.Select(i => MapLineAsync(i, i == arity)))}}
                         );
                         
                         result.ShouldBeT{{arity}}().Value.ShouldBe({{arity + 10}});
                     }
                 """;
    }

    private static string MapLine(int arity, bool isTarget)
    {
        return isTarget
            ? $"u{arity} => new U{arity}(u{arity}.Value + 10)"
            : $"u{arity} => ShouldNotBeCalled(u{arity})";
    }

    private static string MapLineAsync(int arity, bool isTarget)
    {
        return isTarget
            ? $"u{arity} => Task.FromResult(new U{arity}(u{arity}.Value + 10))"
            : $"u{arity} => ShouldNotBeCalledAsync(u{arity})";
    }

    private static string MapLineNull(int arity, bool isTarget)
    {
        return isTarget
            ? "null!"
            : $"u{arity} => ShouldNotBeCalled(u{arity})";
    }

    private static string MapLineNullAsync(int arity, bool isTarget)
    {
        return isTarget
            ? "null!"
            : $"u{arity} => ShouldNotBeCalledAsync(u{arity})";
    }
}