using Toarnbeike.Unions.Utitilies;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates tests for the ProjectT extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class ProjectPartialExtensionsTestsGenerator
{
    private static int[] _arities = null!;
    private static string _union = null!;

    public static string Generate(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{string.Join(',', _arities.Select(i => "U" + i))}>";

        return $$"""
                 {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(ProjectPartialExtensionsTestsGenerator))}}

                 using Toarnbeike.Unions.Extensions;
                 using Toarnbeike.Unions.TestExtensions;
                 using Toarnbeike.Unions.Tests.Unions.TestTypes;
                 // Resharper disable UnusedParameter.Local

                 namespace Toarnbeike.Unions.Tests.Extensions.Project.Generated;

                 public class Project{{arity:D2}}PartialTests
                 {
                 {{string.Join("\n", _arities.Select(FactoryMethod))}}
                 {{HelperMethods()}}
                 {{string.Join("\n", _arities.Select(ProjectT))}}
                 {{string.Join("\n", _arities.Select(ProjectTAsync))}}
                 {{string.Join("\n", _arities.Select(TaskProjectT))}}
                 {{string.Join("\n", _arities.Select(TaskProjectTAsync))}}
                 }
                 """;
    }

    private static string FactoryMethod(int arity)
    {
        return $"    private static {_union} MakeT{arity}(int v) => {_union}.FromT{arity}(new U{arity}(v));";
    }

    private static string HelperMethods()
    {
        return $"""

                    private static int? NullFunc(int original) => null;
                    private static Task<int?> NullAsyncFunc(int original) => Task.FromResult<int?>(null);
                    private static int ShouldNotBeCalled(int original) => throw new ShouldNotBeCalledException();
                    private static Task<int> ShouldNotBeCalledAsync(int original) => throw new ShouldNotBeCalledException();
                """;
    }

    private static string ProjectT(int arity)
    {
        var otherArity = arity == 1 ? 2 : 1;

        return $$"""

                     [Test]
                     public void ProjectT{{arity}}_Should_Invoke_T{{arity}}_Projection()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         var result = union.ProjectT{{arity}}(u{{arity}} => u{{arity}}.Value + 10);
                         
                         result.ShouldBeT{{arity}}({{arity + 10}});
                     }
                 {{string.Join("\n", _arities.Where(a => a != arity).Select(a => NotInvoke(a, arity)))}}

                     [Test]
                     public void ProjectT{{arity}}_Throws_When_T{{arity}}_Projection_ReturnsNull()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         
                         Should.Throw<ArgumentNullException>(() => union.ProjectT{{arity}}(u{{arity}} => NullFunc(u{{arity}}.Value)));
                     }
                 """;
    }

    private static string NotInvoke(int otherArity, int testedArity)
    {
        return $$"""

                [Test]
                public void ProjectT{{testedArity}}_Should_NotInvoke_WhenT{{otherArity}}()
                {
                    var union = MakeT{{otherArity}}({{otherArity}});

                    var result = union.ProjectT{{testedArity}}(u{{testedArity}} => ShouldNotBeCalled(u{{testedArity}}.Value));

                    result.ShouldBeT{{otherArity}}().Value.ShouldBe({{otherArity}});
                }
            """;
    }

    private static string ProjectTAsync(int arity)
    {
        var otherArity = arity == 1 ? 2 : 1;

        return $$"""

                     [Test]
                     public async Task ProjectT{{arity}}Async_Should_Invoke_T{{arity}}_Projection()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         var result = await union.ProjectT{{arity}}Async(u{{arity}} => Task.FromResult(u{{arity}}.Value + 10));
                         
                         result.ShouldBeT{{arity}}({{arity + 10}});
                     }
                 {{string.Join("\n", _arities.Where(a => a != arity).Select(a => NotInvokeAsync(a, arity)))}}
                 

                     [Test]
                     public async Task ProjectT{{arity}}Async_Throws_When_T{{arity}}_Projection_ReturnsNull()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         
                         await Should.ThrowAsync<ArgumentNullException>(() => union.ProjectT{{arity}}Async(u{{arity}} => NullAsyncFunc(u{{arity}}.Value)));
                     }
                 """;
    }

    private static string NotInvokeAsync(int otherArity, int testedArity)
    {
        return $$"""

                [Test]
                public async Task ProjectT{{testedArity}}Async_Should_NotInvoke_WhenT{{otherArity}}()
                {
                    var union = MakeT{{otherArity}}({{otherArity}});

                    var result = await union.ProjectT{{testedArity}}Async(u{{testedArity}} => ShouldNotBeCalledAsync(u{{testedArity}}.Value));

                    result.ShouldBeT{{otherArity}}().Value.ShouldBe({{otherArity}});
                }
            """;
    }

    private static string TaskProjectT(int arity)
    {
        return $$"""

                     [Test]
                     public async Task TaskProjectT{{arity}}_Should_Invoke_T{{arity}}_Projection()
                     {
                         var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                         var result = await task.ProjectT{{arity}}(u{{arity}} => u{{arity}}.Value + 10);
                         
                         result.ShouldBeT{{arity}}({{arity + 10}});
                     }
                 """;
    }

    private static string TaskProjectTAsync(int arity)
    {

        return $$"""

                     [Test]
                     public async Task TaskProjectT{{arity}}Async_Should_Invoke_T{{arity}}_Projection()
                     {
                         var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                         var result = await task.ProjectT{{arity}}Async(u{{arity}} => Task.FromResult(u{{arity}}.Value + 10));
                         
                         result.ShouldBeT{{arity}}({{arity + 10}});
                     }
                 """;
    }
}
