using Toarnbeike.Unions.Utitilies;

namespace Toarnbeike.Unions.Generators;

/// <summary>
/// Generates tests for the Switch extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class SwitchExtensionsTestsGenerator
{
    private static int[] _arities = null!;
    private static string _union = null!;
    private static string _unionDefinition = null!;

    public static string Generate(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{string.Join(',', _arities.Select(i => "U" + i))}>";
        _unionDefinition = $"Union<{string.Join(", ", _arities.Select(i => "T" + i))}>";

        return $$"""
            {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(SwitchExtensionsTestsGenerator))}}

            using Toarnbeike.Unions.Extensions;
            using Toarnbeike.Unions.Tests.Unions.TestTypes;

            namespace Toarnbeike.Unions.Tests.Extensions.Switch.Generated;

            public class Switch{{arity:D2}}ExtensionTests
            {
            {{string.Join("\n", _arities.Select(FactoryMethod))}}
            {{string.Join("\n", _arities.Select(SwitchTest))}}
            {{string.Join("\n", _arities.Select(SwitchNullTest))}}
            {{SwitchInvalidIndex()}}
            {{string.Join("\n", _arities.Select(SwitchAsyncTest))}}
            {{string.Join("\n", _arities.Select(SwitchNullAsyncTest))}}
            {{SwitchInvalidIndexAsync()}}
            {{string.Join("\n", _arities.Select(TaskSwitchTest))}}
            {{string.Join("\n", _arities.Select(TaskSwitchAsyncTest))}}
            }
            """;
    }

    private static string FactoryMethod(int arity)
    {
        return $"    private static {_union} MakeT{arity}(int v) => {_union}.FromT{arity}(new U{arity}(v));";
    }

    private static string SwitchTest(int arity)
    {
        return $$"""

                [Test]
                public void Switch_Should_Invoke_T{{arity}}_Action()
                {
                    var union = MakeT{{arity}}({{arity}});
                    var actual = "";

                    union.Switch(
            {{string.Join(",\n", _arities.Select(i => SwitchLine(i, i == arity)))}}
                    );

                    actual.ShouldBe("T{{arity}}:{{arity}}");
                }
            """;
    }

    private static string SwitchAsyncTest(int arity)
    {
        return $$"""

                [Test]
                public async Task SwitchAsync_Should_Invoke_T{{arity}}_Task()
                {
                    var union = MakeT{{arity}}({{arity}});
                    var actual = "";

                    await union.SwitchAsync(
            {{string.Join(",\n", _arities.Select(i => SwitchAsyncLine(i, i == arity)))}}
                    );

                    actual.ShouldBe("T{{arity}}:{{arity}}");
                }
            """;
    }

    private static string TaskSwitchTest(int arity)
    {
        return $$"""

                [Test]
                public async Task TaskSwitch_Should_Invoke_T{{arity}}_Action()
                {
                    var task = Task.FromResult(MakeT{{arity}}({{arity}}));
                    var actual = "";

                    await task.Switch(
            {{string.Join(",\n", _arities.Select(i => SwitchLine(i, i == arity)))}}
                    );
            
                    actual.ShouldBe("T{{arity}}:{{arity}}");
                }
            """;
    }

    private static string TaskSwitchAsyncTest(int arity)
    {
        return $$"""

                [Test]
                public async Task TaskSwitchAsync_Should_Invoke_T{{arity}}_Handler()
                {
                    var task = Task.FromResult(MakeT{{arity}}({{arity}}));
                    var actual = "";

                    await task.SwitchAsync(
            {{string.Join(",\n", _arities.Select(i => SwitchAsyncLine(i, i == arity)))}}
                    );

                    actual.ShouldBe("T{{arity}}:{{arity}}");
                }
            """;
    }

    private static string SwitchLine(int arity, bool isTarget)
    {
        return isTarget
            ? $$"""
                        t{{arity}} => actual = $"T{{arity}}:{t{{arity}}.Value}"
            """
            : "            _ => throw new ShouldNotBeCalledException()";
    }

    private static string SwitchAsyncLine(int arity, bool isTarget)
    {
        return isTarget
            ? $$"""
                        async t{{arity}} => { await Task.Yield(); actual = $"T{{arity}}:{t{{arity}}.Value}"; }
            """
            : "            _ => throw new ShouldNotBeCalledException()";
    }

    private static string SwitchNullTest(int arity)
    {
        return $$"""

                [Test]
                public void Switch_Should_Throw_On_Null_T{{arity}}_Action()
                {
                    var union = MakeT{{arity}}({{arity}});
                    Should.Throw<ArgumentNullException>(() => union.Switch({{NullArguments(arity)}}));
                }
            """;
    }

    private static string SwitchNullAsyncTest(int arity)
    {
        return $$"""

                [Test]
                public async Task SwitchAsync_Should_Throw_On_Null_T{{arity}}_Task()
                {
                    var union = MakeT{{arity}}({{arity}});
                    await Should.ThrowAsync<ArgumentNullException>(async () => await union.SwitchAsync({{NullAsyncArguments(arity)}}));
                }
            """;
    }

    private static string SwitchInvalidIndex()
    {
        return $$"""

                [Test]
                public void Switch_Should_Throw_On_Invalid_Index()
                {
                    var invalid = default({{_union}});

                    var ex = Should.Throw<InvalidOperationException>(() => invalid.Switch({{ValidArguments()}}));
                    ex.Message.ShouldBe("Union index 0 is invalid for {{_unionDefinition}}.");
                }
            """;
    }

    private static string SwitchInvalidIndexAsync()
    {
        return $$"""

                [Test]
                public async Task SwitchAsync_Should_Throw_On_Invalid_Index()
                {
                    var invalid = default({{_union}});

                    var ex = await Should.ThrowAsync<InvalidOperationException>(async () => await invalid.SwitchAsync({{ValidAsyncArguments()}}));
                    ex.Message.ShouldBe("Union index 0 is invalid for {{_unionDefinition}}.");
                }
            """;
    }

    private static string NullArguments(int arity)
    {
        return string.Join(", ", _arities.Select(i => i == arity ? "null!" : $"_ => {{ }}"));
    }

    private static string NullAsyncArguments(int arity)
    {
        return string.Join(", ", _arities.Select(i => i == arity ? "null!" : $"async _ => await Task.Yield()"));
    }

    private static string ValidArguments()
    {
        return string.Join(",", _arities.Select(i => $"_ => {{ }}"));
    }

    private static string ValidAsyncArguments()
    {
        return string.Join(", ", _arities.Select(i => $"async _ => await Task.Yield()"));
    }
}

