using Toarnbeike.Unions.Tests.Utitilies;

namespace Toarnbeike.Unions.Tests.Generators;

/// <summary>
/// Generates tests for the Tap extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class TapExtensionsTestsGenerator
{
    private static int[] _arities = null!;
    private static string _union = null!;

    public static string Generate(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{string.Join(',', _arities.Select(i => "U" + i))}>";

        return $$"""
                 {{AutoGeneratedMessageGenerator.GetAutoGeneratedMessage(nameof(TapExtensionsTestsGenerator))}}

                 using Toarnbeike.Unions.Generic;
                 using Toarnbeike.Unions.Generic.Extensions;
                 using Toarnbeike.Unions.Generic.TestExtensions;
                 using Toarnbeike.Unions.Tests.TestTypes;
                 // Resharper disable UnusedParameter.Local

                 namespace Toarnbeike.Unions.Tests.Extensions.Tap.Generated;

                 public class Tap{{arity:D2}}Tests
                 {
                 {{string.Join("\n", _arities.Select(FactoryMethod))}}
                 {{HelperMethods()}}
                 {{string.Join("\n", _arities.Select(Tap))}}
                 {{string.Join("\n", _arities.Select(TapAsync))}}
                 {{string.Join("\n", _arities.Select(TaskTap))}}
                 {{string.Join("\n", _arities.Select(TaskTapAsync))}}
                 }
                 """;
    }
    private static string FactoryMethod(int arity)
    {
        return $"    private static {_union} MakeT{arity}(int v) => {_union}.FromT{arity}(new U{arity}(v));";
    }

    private static string HelperMethods()
    {
        return $"""

                    private static {_union} ShouldNotBeCalled(int original) => throw new ShouldNotBeCalledException();
                    private static Task<{_union}> ShouldNotBeCalledAsync(int original) => throw new ShouldNotBeCalledException();
                """;
    }

    private static string Tap(int arity)
    {
        var otherArity = arity == 1 ? 2 : 1;

        return $$"""

                     [Test]
                     public void TapT{{arity}}_Should_Invoke_T{{arity}}Func_WhenT{{arity}}()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         var actual = "";

                         var result = union.TapT{{arity}}(u{{arity}} => actual = $"U{{arity}}:{u{{arity}}.Value}");
                         
                         result.ShouldBe(union);
                         actual.ShouldBe("U{{arity}}:{{arity}}");
                     }

                     [Test]
                     public void TapT{{arity}}_Should_NotInvoke_WhenT{{otherArity}}()
                     {
                         var union = MakeT{{otherArity}}({{otherArity}});

                         var result = union.TapT{{arity}}(u{{arity}} => ShouldNotBeCalled(u{{arity}}.Value));

                         result.ShouldBe(union);
                     }

                     [Test]
                     public void TapT{{arity}}_Throws_When_T{{arity}}Func_ReturnsNull()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         
                         Should.Throw<ArgumentNullException>(() => union.TapT{{arity}}(null!));
                     }
                 """;
    }

    private static string TapAsync(int arity)
    {
        var otherArity = arity == 1 ? 2 : 1;

        return $$"""

                     [Test]
                     public async Task TapT{{arity}}Async_Should_Invoke_T{{arity}}Func_WhenT{{arity}}()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         var actual = "";

                         var result = await union.TapT{{arity}}Async(async u{{arity}} => { await Task.Yield(); actual = $"U{{arity}}:{u{{arity}}.Value}"; });

                         result.ShouldBe(union);
                         actual.ShouldBe("U{{arity}}:{{arity}}");
                     }

                     [Test]
                     public async Task TapT{{arity}}Async_Should_NotInvoke_WhenT{{otherArity}}()
                     {
                         var union = MakeT{{otherArity}}({{otherArity}});
                 
                         var result = await union.TapT{{arity}}Async(u{{arity}} => ShouldNotBeCalledAsync(u{{arity}}.Value));
                 
                         result.ShouldBe(union);
                     }

                     [Test]
                     public async Task TapT{{arity}}Async_Throws_When_T{{arity}}Func_ReturnsNull()
                     {
                         var union = MakeT{{arity}}({{arity}});
                         
                         await Should.ThrowAsync<ArgumentNullException>(() => union.TapT{{arity}}Async(null!));
                     }
                 """;
    }

    private static string TaskTap(int arity)
    {
        return $$"""

                     [Test]
                     public async Task TaskTapT{{arity}}_Should_Invoke_T{{arity}}Func()
                     {
                         var task = Task.FromResult(MakeT{{arity}}({{arity}}));
                         var actual = "";

                         var result = await task.TapT{{arity}}(u{{arity}} => actual = $"U{{arity}}:{u{{arity}}.Value}");
                         
                         result.ShouldBeT{{arity}}().Value.ShouldBe({{arity}});
                         actual.ShouldBe("U{{arity}}:{{arity}}");
                     }
                 """;
    }


    private static string TaskTapAsync(int arity)
    {
        return $$"""

                     [Test]
                     public async Task TaskTapT{{arity}}Async_Should_Invoke_T{{arity}}Func()
                     {
                         var task = Task.FromResult(MakeT{{arity}}({{arity}}));
                         var actual = "";
                 
                         var result = await task.TapT{{arity}}Async(async u{{arity}} => { await Task.Yield(); actual = $"U{{arity}}:{u{{arity}}.Value}"; });
                 
                         result.ShouldBeT{{arity}}().Value.ShouldBe({{arity}});
                         actual.ShouldBe("U{{arity}}:{{arity}}");
                     }
                 """;
    }
}