# nullable enable

// <auto-generated>
//   This file was generated by Toarnbeike.Unions.StaticGenerator.
//   Generator: UnionGenerator (v. 1.3.0)
//   Created: 2026-02-01 12:08:01Z
//   This is an auto-generated file. Do not modify.
// </auto-generated>

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Toarnbeike.Unions.Generic;

#region Union<T1, T2>

/// <summary>
/// Union type with 2 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion

#region Union<T1, T2, T3>

/// <summary>
/// Union type with 3 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2, T3>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3> FromT3(T3 value) => new(3, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Indicates whether the union is in T3 state.
    /// </summary>
    public bool IsT3 => Index == 3;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T3 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT3"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T3 state.</exception>
    internal T3 AsT3 => Index == 3 ? (T3)_value : throw new InvalidOperationException("Union is not in T3 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T3 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T3 state; otherwise, null.</param>
    public bool TryGetT3([MaybeNullWhen(false)] out T3 value)
    {
        var isMatch = Index == 3;
        value = isMatch ? (T3)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
           3 => $"T3 ({typeof(T3).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion

#region Union<T1, T2, T3, T4>

/// <summary>
/// Union type with 4 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2, T3, T4>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4> FromT3(T3 value) => new(3, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4> FromT4(T4 value) => new(4, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Indicates whether the union is in T3 state.
    /// </summary>
    public bool IsT3 => Index == 3;

    /// <summary>
    /// Indicates whether the union is in T4 state.
    /// </summary>
    public bool IsT4 => Index == 4;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T3 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT3"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T3 state.</exception>
    internal T3 AsT3 => Index == 3 ? (T3)_value : throw new InvalidOperationException("Union is not in T3 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T4 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT4"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T4 state.</exception>
    internal T4 AsT4 => Index == 4 ? (T4)_value : throw new InvalidOperationException("Union is not in T4 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T3 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T3 state; otherwise, null.</param>
    public bool TryGetT3([MaybeNullWhen(false)] out T3 value)
    {
        var isMatch = Index == 3;
        value = isMatch ? (T3)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T4 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T4 state; otherwise, null.</param>
    public bool TryGetT4([MaybeNullWhen(false)] out T4 value)
    {
        var isMatch = Index == 4;
        value = isMatch ? (T4)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
           3 => $"T3 ({typeof(T3).Name}) = {_value}",
           4 => $"T4 ({typeof(T4).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion

#region Union<T1, T2, T3, T4, T5>

/// <summary>
/// Union type with 5 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2, T3, T4, T5>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5> FromT3(T3 value) => new(3, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5> FromT4(T4 value) => new(4, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5> FromT5(T5 value) => new(5, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Indicates whether the union is in T3 state.
    /// </summary>
    public bool IsT3 => Index == 3;

    /// <summary>
    /// Indicates whether the union is in T4 state.
    /// </summary>
    public bool IsT4 => Index == 4;

    /// <summary>
    /// Indicates whether the union is in T5 state.
    /// </summary>
    public bool IsT5 => Index == 5;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T3 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT3"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T3 state.</exception>
    internal T3 AsT3 => Index == 3 ? (T3)_value : throw new InvalidOperationException("Union is not in T3 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T4 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT4"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T4 state.</exception>
    internal T4 AsT4 => Index == 4 ? (T4)_value : throw new InvalidOperationException("Union is not in T4 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T5 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT5"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T5 state.</exception>
    internal T5 AsT5 => Index == 5 ? (T5)_value : throw new InvalidOperationException("Union is not in T5 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T3 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T3 state; otherwise, null.</param>
    public bool TryGetT3([MaybeNullWhen(false)] out T3 value)
    {
        var isMatch = Index == 3;
        value = isMatch ? (T3)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T4 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T4 state; otherwise, null.</param>
    public bool TryGetT4([MaybeNullWhen(false)] out T4 value)
    {
        var isMatch = Index == 4;
        value = isMatch ? (T4)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T5 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T5 state; otherwise, null.</param>
    public bool TryGetT5([MaybeNullWhen(false)] out T5 value)
    {
        var isMatch = Index == 5;
        value = isMatch ? (T5)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
           3 => $"T3 ({typeof(T3).Name}) = {_value}",
           4 => $"T4 ({typeof(T4).Name}) = {_value}",
           5 => $"T5 ({typeof(T5).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion

#region Union<T1, T2, T3, T4, T5, T6>

/// <summary>
/// Union type with 6 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2, T3, T4, T5, T6>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6> FromT3(T3 value) => new(3, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6> FromT4(T4 value) => new(4, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6> FromT5(T5 value) => new(5, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6> FromT6(T6 value) => new(6, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Indicates whether the union is in T3 state.
    /// </summary>
    public bool IsT3 => Index == 3;

    /// <summary>
    /// Indicates whether the union is in T4 state.
    /// </summary>
    public bool IsT4 => Index == 4;

    /// <summary>
    /// Indicates whether the union is in T5 state.
    /// </summary>
    public bool IsT5 => Index == 5;

    /// <summary>
    /// Indicates whether the union is in T6 state.
    /// </summary>
    public bool IsT6 => Index == 6;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T3 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT3"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T3 state.</exception>
    internal T3 AsT3 => Index == 3 ? (T3)_value : throw new InvalidOperationException("Union is not in T3 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T4 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT4"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T4 state.</exception>
    internal T4 AsT4 => Index == 4 ? (T4)_value : throw new InvalidOperationException("Union is not in T4 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T5 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT5"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T5 state.</exception>
    internal T5 AsT5 => Index == 5 ? (T5)_value : throw new InvalidOperationException("Union is not in T5 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T6 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT6"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T6 state.</exception>
    internal T6 AsT6 => Index == 6 ? (T6)_value : throw new InvalidOperationException("Union is not in T6 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T3 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T3 state; otherwise, null.</param>
    public bool TryGetT3([MaybeNullWhen(false)] out T3 value)
    {
        var isMatch = Index == 3;
        value = isMatch ? (T3)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T4 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T4 state; otherwise, null.</param>
    public bool TryGetT4([MaybeNullWhen(false)] out T4 value)
    {
        var isMatch = Index == 4;
        value = isMatch ? (T4)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T5 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T5 state; otherwise, null.</param>
    public bool TryGetT5([MaybeNullWhen(false)] out T5 value)
    {
        var isMatch = Index == 5;
        value = isMatch ? (T5)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T6 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T6 state; otherwise, null.</param>
    public bool TryGetT6([MaybeNullWhen(false)] out T6 value)
    {
        var isMatch = Index == 6;
        value = isMatch ? (T6)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
           3 => $"T3 ({typeof(T3).Name}) = {_value}",
           4 => $"T4 ({typeof(T4).Name}) = {_value}",
           5 => $"T5 ({typeof(T5).Name}) = {_value}",
           6 => $"T6 ({typeof(T6).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion

#region Union<T1, T2, T3, T4, T5, T6, T7>

/// <summary>
/// Union type with 7 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2, T3, T4, T5, T6, T7>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT3(T3 value) => new(3, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT4(T4 value) => new(4, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT5(T5 value) => new(5, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT6(T6 value) => new(6, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7> FromT7(T7 value) => new(7, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Indicates whether the union is in T3 state.
    /// </summary>
    public bool IsT3 => Index == 3;

    /// <summary>
    /// Indicates whether the union is in T4 state.
    /// </summary>
    public bool IsT4 => Index == 4;

    /// <summary>
    /// Indicates whether the union is in T5 state.
    /// </summary>
    public bool IsT5 => Index == 5;

    /// <summary>
    /// Indicates whether the union is in T6 state.
    /// </summary>
    public bool IsT6 => Index == 6;

    /// <summary>
    /// Indicates whether the union is in T7 state.
    /// </summary>
    public bool IsT7 => Index == 7;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T3 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT3"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T3 state.</exception>
    internal T3 AsT3 => Index == 3 ? (T3)_value : throw new InvalidOperationException("Union is not in T3 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T4 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT4"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T4 state.</exception>
    internal T4 AsT4 => Index == 4 ? (T4)_value : throw new InvalidOperationException("Union is not in T4 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T5 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT5"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T5 state.</exception>
    internal T5 AsT5 => Index == 5 ? (T5)_value : throw new InvalidOperationException("Union is not in T5 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T6 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT6"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T6 state.</exception>
    internal T6 AsT6 => Index == 6 ? (T6)_value : throw new InvalidOperationException("Union is not in T6 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T7 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT7"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T7 state.</exception>
    internal T7 AsT7 => Index == 7 ? (T7)_value : throw new InvalidOperationException("Union is not in T7 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T3 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T3 state; otherwise, null.</param>
    public bool TryGetT3([MaybeNullWhen(false)] out T3 value)
    {
        var isMatch = Index == 3;
        value = isMatch ? (T3)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T4 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T4 state; otherwise, null.</param>
    public bool TryGetT4([MaybeNullWhen(false)] out T4 value)
    {
        var isMatch = Index == 4;
        value = isMatch ? (T4)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T5 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T5 state; otherwise, null.</param>
    public bool TryGetT5([MaybeNullWhen(false)] out T5 value)
    {
        var isMatch = Index == 5;
        value = isMatch ? (T5)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T6 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T6 state; otherwise, null.</param>
    public bool TryGetT6([MaybeNullWhen(false)] out T6 value)
    {
        var isMatch = Index == 6;
        value = isMatch ? (T6)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T7 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T7 state; otherwise, null.</param>
    public bool TryGetT7([MaybeNullWhen(false)] out T7 value)
    {
        var isMatch = Index == 7;
        value = isMatch ? (T7)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
           3 => $"T3 ({typeof(T3).Name}) = {_value}",
           4 => $"T4 ({typeof(T4).Name}) = {_value}",
           5 => $"T5 ({typeof(T5).Name}) = {_value}",
           6 => $"T6 ({typeof(T6).Name}) = {_value}",
           7 => $"T7 ({typeof(T7).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion

#region Union<T1, T2, T3, T4, T5, T6, T7, T8>

/// <summary>
/// Union type with 8 variants.
/// </summary>
[DebuggerDisplay("{DebuggerToString(),nq}")]
public readonly record struct Union<T1, T2, T3, T4, T5, T6, T7, T8>
{
    /// <summary>
    /// The value stored in the union.
    /// </summary>
    private readonly object _value;
    
    /// <summary>
    /// The index of the variant stored in the union.
    /// </summary>
    internal byte Index { get; }
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT1(T1 value) => new(1, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT2(T2 value) => new(2, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT3(T3 value) => new(3, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT4(T4 value) => new(4, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT5(T5 value) => new(5, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT6(T6 value) => new(6, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT7(T7 value) => new(7, value);
    
    /// <summary>
    /// Creates a new union instance by providing the value to store in it.
    /// </summary>
    /// <param name="value">The value to store in the union.</param>
    public static Union<T1, T2, T3, T4, T5, T6, T7, T8> FromT8(T8 value) => new(8, value);
    
    /// <summary>
    /// Indicates whether the union is in T1 state.
    /// </summary>
    public bool IsT1 => Index == 1;

    /// <summary>
    /// Indicates whether the union is in T2 state.
    /// </summary>
    public bool IsT2 => Index == 2;

    /// <summary>
    /// Indicates whether the union is in T3 state.
    /// </summary>
    public bool IsT3 => Index == 3;

    /// <summary>
    /// Indicates whether the union is in T4 state.
    /// </summary>
    public bool IsT4 => Index == 4;

    /// <summary>
    /// Indicates whether the union is in T5 state.
    /// </summary>
    public bool IsT5 => Index == 5;

    /// <summary>
    /// Indicates whether the union is in T6 state.
    /// </summary>
    public bool IsT6 => Index == 6;

    /// <summary>
    /// Indicates whether the union is in T7 state.
    /// </summary>
    public bool IsT7 => Index == 7;

    /// <summary>
    /// Indicates whether the union is in T8 state.
    /// </summary>
    public bool IsT8 => Index == 8;

    /// <summary>
    /// Gets the value of the union if it is in the T1 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT1"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T1 state.</exception>
    internal T1 AsT1 => Index == 1 ? (T1)_value : throw new InvalidOperationException("Union is not in T1 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T2 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT2"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T2 state.</exception>
    internal T2 AsT2 => Index == 2 ? (T2)_value : throw new InvalidOperationException("Union is not in T2 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T3 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT3"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T3 state.</exception>
    internal T3 AsT3 => Index == 3 ? (T3)_value : throw new InvalidOperationException("Union is not in T3 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T4 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT4"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T4 state.</exception>
    internal T4 AsT4 => Index == 4 ? (T4)_value : throw new InvalidOperationException("Union is not in T4 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T5 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT5"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T5 state.</exception>
    internal T5 AsT5 => Index == 5 ? (T5)_value : throw new InvalidOperationException("Union is not in T5 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T6 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT6"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T6 state.</exception>
    internal T6 AsT6 => Index == 6 ? (T6)_value : throw new InvalidOperationException("Union is not in T6 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T7 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT7"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T7 state.</exception>
    internal T7 AsT7 => Index == 7 ? (T7)_value : throw new InvalidOperationException("Union is not in T7 state.");
    
    /// <summary>
    /// Gets the value of the union if it is in the T8 state; otherwise, throws an <see cref="InvalidOperationException"/>.
    /// </summary>
    /// <remarks>
    /// This method is explicitly internal. For external use, either use <see cref="TryGetT8"/>, or the Match or Switch methods.
    /// </remarks>
    /// <exception cref="InvalidOperationException">Thrown if the union is not in the T8 state.</exception>
    internal T8 AsT8 => Index == 8 ? (T8)_value : throw new InvalidOperationException("Union is not in T8 state.");
    
    /// <summary>
    /// Tries to get the value of the union if it is in the T1 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T1 state; otherwise, null.</param>
    public bool TryGetT1([MaybeNullWhen(false)] out T1 value)
    {
        var isMatch = Index == 1;
        value = isMatch ? (T1)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T2 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T2 state; otherwise, null.</param>
    public bool TryGetT2([MaybeNullWhen(false)] out T2 value)
    {
        var isMatch = Index == 2;
        value = isMatch ? (T2)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T3 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T3 state; otherwise, null.</param>
    public bool TryGetT3([MaybeNullWhen(false)] out T3 value)
    {
        var isMatch = Index == 3;
        value = isMatch ? (T3)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T4 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T4 state; otherwise, null.</param>
    public bool TryGetT4([MaybeNullWhen(false)] out T4 value)
    {
        var isMatch = Index == 4;
        value = isMatch ? (T4)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T5 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T5 state; otherwise, null.</param>
    public bool TryGetT5([MaybeNullWhen(false)] out T5 value)
    {
        var isMatch = Index == 5;
        value = isMatch ? (T5)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T6 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T6 state; otherwise, null.</param>
    public bool TryGetT6([MaybeNullWhen(false)] out T6 value)
    {
        var isMatch = Index == 6;
        value = isMatch ? (T6)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T7 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T7 state; otherwise, null.</param>
    public bool TryGetT7([MaybeNullWhen(false)] out T7 value)
    {
        var isMatch = Index == 7;
        value = isMatch ? (T7)_value : default;
        return isMatch;
    }

    /// <summary>
    /// Tries to get the value of the union if it is in the T8 state.
    /// </summary>
    /// <param name="value">The value stored in the union if it is in the T8 state; otherwise, null.</param>
    public bool TryGetT8([MaybeNullWhen(false)] out T8 value)
    {
        var isMatch = Index == 8;
        value = isMatch ? (T8)_value : default;
        return isMatch;
    }

    private Union(byte index, object? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        (Index, _value) = (index, value);
    }

    /// <summary>
    /// Debugger string representation of the union.
    /// </summary>
    internal string DebuggerToString()
    {
        return Index switch
        {
           1 => $"T1 ({typeof(T1).Name}) = {_value}",
           2 => $"T2 ({typeof(T2).Name}) = {_value}",
           3 => $"T3 ({typeof(T3).Name}) = {_value}",
           4 => $"T4 ({typeof(T4).Name}) = {_value}",
           5 => $"T5 ({typeof(T5).Name}) = {_value}",
           6 => $"T6 ({typeof(T6).Name}) = {_value}",
           7 => $"T7 ({typeof(T7).Name}) = {_value}",
           8 => $"T8 ({typeof(T8).Name}) = {_value}",
            _ => "<uninitialized>"
        };
    }
}
#endregion