# nullable enable

// <auto-generated>
//   This file was generated by Toarnbeike.Unions.StaticGenerator.
//   Generator: PartitionExtensionsGenerator (v. 1.0.0)
//   Created: 2025-12-17 16:17:36Z
//   This is an auto-generated file. Do not modify.
// </auto-generated>

using Toarnbeike.Unions.Extensions;

namespace Toarnbeike.Unions.Collections;

/// <summary>
/// Partition: extension methods to partition collections of unions into collections of their constituent types.
/// </summary>
public static class PartitionExtensions
{
    #region Partition Extensions for Union<T1, T2>
    extension<T1, T2>(IEnumerable<Union<T1, T2>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add);
            }

            return (t1Set, t2Set);
        }
    }

    #endregion

    #region Partition Extensions for Union<T1, T2, T3>
    extension<T1, T2, T3>(IEnumerable<Union<T1, T2, T3>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

       /// <summary>
       /// Select all elements of type T3 from the collection of unions.
       /// </summary>
       public IEnumerable<T3> SelectT3()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT3).Select(union => union.AsT3);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s, IReadOnlyList<T3> T3s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();
            var t3Set = new List<T3>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add, t3Set.Add);
            }

            return (t1Set, t2Set, t3Set);
        }
    }

    #endregion

    #region Partition Extensions for Union<T1, T2, T3, T4>
    extension<T1, T2, T3, T4>(IEnumerable<Union<T1, T2, T3, T4>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

       /// <summary>
       /// Select all elements of type T3 from the collection of unions.
       /// </summary>
       public IEnumerable<T3> SelectT3()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT3).Select(union => union.AsT3);
       }

       /// <summary>
       /// Select all elements of type T4 from the collection of unions.
       /// </summary>
       public IEnumerable<T4> SelectT4()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT4).Select(union => union.AsT4);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s, IReadOnlyList<T3> T3s, IReadOnlyList<T4> T4s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();
            var t3Set = new List<T3>();
            var t4Set = new List<T4>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add, t3Set.Add, t4Set.Add);
            }

            return (t1Set, t2Set, t3Set, t4Set);
        }
    }

    #endregion

    #region Partition Extensions for Union<T1, T2, T3, T4, T5>
    extension<T1, T2, T3, T4, T5>(IEnumerable<Union<T1, T2, T3, T4, T5>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

       /// <summary>
       /// Select all elements of type T3 from the collection of unions.
       /// </summary>
       public IEnumerable<T3> SelectT3()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT3).Select(union => union.AsT3);
       }

       /// <summary>
       /// Select all elements of type T4 from the collection of unions.
       /// </summary>
       public IEnumerable<T4> SelectT4()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT4).Select(union => union.AsT4);
       }

       /// <summary>
       /// Select all elements of type T5 from the collection of unions.
       /// </summary>
       public IEnumerable<T5> SelectT5()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT5).Select(union => union.AsT5);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s, IReadOnlyList<T3> T3s, IReadOnlyList<T4> T4s, IReadOnlyList<T5> T5s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();
            var t3Set = new List<T3>();
            var t4Set = new List<T4>();
            var t5Set = new List<T5>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add, t3Set.Add, t4Set.Add, t5Set.Add);
            }

            return (t1Set, t2Set, t3Set, t4Set, t5Set);
        }
    }

    #endregion

    #region Partition Extensions for Union<T1, T2, T3, T4, T5, T6>
    extension<T1, T2, T3, T4, T5, T6>(IEnumerable<Union<T1, T2, T3, T4, T5, T6>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

       /// <summary>
       /// Select all elements of type T3 from the collection of unions.
       /// </summary>
       public IEnumerable<T3> SelectT3()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT3).Select(union => union.AsT3);
       }

       /// <summary>
       /// Select all elements of type T4 from the collection of unions.
       /// </summary>
       public IEnumerable<T4> SelectT4()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT4).Select(union => union.AsT4);
       }

       /// <summary>
       /// Select all elements of type T5 from the collection of unions.
       /// </summary>
       public IEnumerable<T5> SelectT5()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT5).Select(union => union.AsT5);
       }

       /// <summary>
       /// Select all elements of type T6 from the collection of unions.
       /// </summary>
       public IEnumerable<T6> SelectT6()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT6).Select(union => union.AsT6);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s, IReadOnlyList<T3> T3s, IReadOnlyList<T4> T4s, IReadOnlyList<T5> T5s, IReadOnlyList<T6> T6s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();
            var t3Set = new List<T3>();
            var t4Set = new List<T4>();
            var t5Set = new List<T5>();
            var t6Set = new List<T6>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add, t3Set.Add, t4Set.Add, t5Set.Add, t6Set.Add);
            }

            return (t1Set, t2Set, t3Set, t4Set, t5Set, t6Set);
        }
    }

    #endregion

    #region Partition Extensions for Union<T1, T2, T3, T4, T5, T6, T7>
    extension<T1, T2, T3, T4, T5, T6, T7>(IEnumerable<Union<T1, T2, T3, T4, T5, T6, T7>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

       /// <summary>
       /// Select all elements of type T3 from the collection of unions.
       /// </summary>
       public IEnumerable<T3> SelectT3()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT3).Select(union => union.AsT3);
       }

       /// <summary>
       /// Select all elements of type T4 from the collection of unions.
       /// </summary>
       public IEnumerable<T4> SelectT4()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT4).Select(union => union.AsT4);
       }

       /// <summary>
       /// Select all elements of type T5 from the collection of unions.
       /// </summary>
       public IEnumerable<T5> SelectT5()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT5).Select(union => union.AsT5);
       }

       /// <summary>
       /// Select all elements of type T6 from the collection of unions.
       /// </summary>
       public IEnumerable<T6> SelectT6()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT6).Select(union => union.AsT6);
       }

       /// <summary>
       /// Select all elements of type T7 from the collection of unions.
       /// </summary>
       public IEnumerable<T7> SelectT7()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT7).Select(union => union.AsT7);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s, IReadOnlyList<T3> T3s, IReadOnlyList<T4> T4s, IReadOnlyList<T5> T5s, IReadOnlyList<T6> T6s, IReadOnlyList<T7> T7s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();
            var t3Set = new List<T3>();
            var t4Set = new List<T4>();
            var t5Set = new List<T5>();
            var t6Set = new List<T6>();
            var t7Set = new List<T7>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add, t3Set.Add, t4Set.Add, t5Set.Add, t6Set.Add, t7Set.Add);
            }

            return (t1Set, t2Set, t3Set, t4Set, t5Set, t6Set, t7Set);
        }
    }

    #endregion

    #region Partition Extensions for Union<T1, T2, T3, T4, T5, T6, T7, T8>
    extension<T1, T2, T3, T4, T5, T6, T7, T8>(IEnumerable<Union<T1, T2, T3, T4, T5, T6, T7, T8>> source)
    {

       /// <summary>
       /// Select all elements of type T1 from the collection of unions.
       /// </summary>
       public IEnumerable<T1> SelectT1()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT1).Select(union => union.AsT1);
       }

       /// <summary>
       /// Select all elements of type T2 from the collection of unions.
       /// </summary>
       public IEnumerable<T2> SelectT2()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT2).Select(union => union.AsT2);
       }

       /// <summary>
       /// Select all elements of type T3 from the collection of unions.
       /// </summary>
       public IEnumerable<T3> SelectT3()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT3).Select(union => union.AsT3);
       }

       /// <summary>
       /// Select all elements of type T4 from the collection of unions.
       /// </summary>
       public IEnumerable<T4> SelectT4()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT4).Select(union => union.AsT4);
       }

       /// <summary>
       /// Select all elements of type T5 from the collection of unions.
       /// </summary>
       public IEnumerable<T5> SelectT5()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT5).Select(union => union.AsT5);
       }

       /// <summary>
       /// Select all elements of type T6 from the collection of unions.
       /// </summary>
       public IEnumerable<T6> SelectT6()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT6).Select(union => union.AsT6);
       }

       /// <summary>
       /// Select all elements of type T7 from the collection of unions.
       /// </summary>
       public IEnumerable<T7> SelectT7()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT7).Select(union => union.AsT7);
       }

       /// <summary>
       /// Select all elements of type T8 from the collection of unions.
       /// </summary>
       public IEnumerable<T8> SelectT8()
       {
           ArgumentNullException.ThrowIfNull(source);

           return source.Where(union => union.IsT8).Select(union => union.AsT8);
       }

        /// <summary>
        /// Partitions a collection of unions into separate collections for each type in the union.
        /// </summary>
        /// <param name="source">The source collection of unions.</param>
        /// <returns>A tuple containing a list for each type in the union.</returns>
        public (IReadOnlyList<T1> T1s, IReadOnlyList<T2> T2s, IReadOnlyList<T3> T3s, IReadOnlyList<T4> T4s, IReadOnlyList<T5> T5s, IReadOnlyList<T6> T6s, IReadOnlyList<T7> T7s, IReadOnlyList<T8> T8s) Partition()
        {
            ArgumentNullException.ThrowIfNull(source);

            var t1Set = new List<T1>();
            var t2Set = new List<T2>();
            var t3Set = new List<T3>();
            var t4Set = new List<T4>();
            var t5Set = new List<T5>();
            var t6Set = new List<T6>();
            var t7Set = new List<T7>();
            var t8Set = new List<T8>();

            foreach (var union in source)
            {
                union.Switch(t1Set.Add, t2Set.Add, t3Set.Add, t4Set.Add, t5Set.Add, t6Set.Add, t7Set.Add, t8Set.Add);
            }

            return (t1Set, t2Set, t3Set, t4Set, t5Set, t6Set, t7Set, t8Set);
        }
    }

    #endregion
}