using WriterLibrary;

namespace UnionTestWriters.Writers;

/// <summary>
/// Generates tests for the Map full extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class MapFullExtensionsTestsWriter
{
    private static int[] _arities = null!;
    private static string _union = null!;

    public static string WriteFile(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{string.Join(',', _arities.Select(i => "U" + i))}>";

        return $$"""
                 {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(MapFullExtensionsTestsWriter).FullName!)}}

                 using Toarnbeike.Unions.Generic;
                 using Toarnbeike.Unions.Generic.Extensions;
                 using Toarnbeike.Unions.Generic.TestExtensions;
                 using Toarnbeike.Unions.Tests.TestTypes;

                 namespace Toarnbeike.Unions.Tests.Extensions.Map;

                 public class Map{{arity:D2}}FullTests
                 {
                 {{_arities.Select(FactoryMethod).JoinLines().Indent(1)}}
                 
                 {{HelperMethods().Indent(1)}}
                 
                 {{_arities.Select(Map).JoinLines().Indent(1)}}
                 
                 {{_arities.Select(MapAsync).JoinLines().Indent(1)}}
                 
                 {{_arities.Select(TaskMap).JoinLines().Indent(1)}}
                 
                 {{_arities.Select(TaskMapAsync).JoinLines().Indent(1)}}
                 }
                 """;
    }

    private static string FactoryMethod(int arity)
    {
        return $"private static {_union} MakeT{arity}(int v) => {_union}.FromT{arity}(new U{arity}(v));";
    }

    private static string HelperMethods()
    {
        return """
                private static int? NullFunc(int _) => null;
                private static Task<int?> NullAsyncFunc(int _) => Task.FromResult<int?>(null);
                private static int ShouldNotBeCalled(int _) => throw new ShouldNotBeCalledException();
                private static Task<int> ShouldNotBeCalledAsync(int _) => throw new ShouldNotBeCalledException();
                """;
    }

    private static string Map(int arity)
    {
        return $$"""
                 [Test]
                 public void Map_Should_InvokeT{{arity}}Map()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     var result = union.Map(
                 {{_arities.Select(i => MapLine(i, i == arity)).JoinCommaSeparatedLines().Indent(2)}}
                     );
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 
                 [Test]
                 public void Map_Throws_WhenT{{arity}}_Map_ReturnsNull()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     
                     Should.Throw<ArgumentNullException>(() => union.Map(
                 {{_arities.Select(i => MapLineNull(i, i == arity)).JoinCommaSeparatedLines().Indent(2)}}
                     ));
                 }   
                 """;
    }

    private static string MapAsync(int arity)
    {
        return $$"""
                 [Test]
                 public async Task MapAsync_Should_InvokeT{{arity}}Map()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     var result = await union.MapAsync(
                 {{_arities.Select(i => MapLineAsync(i, i == arity)).JoinCommaSeparatedLines().Indent(2)}}
                     );
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 
                 [Test]
                 public async Task MapAsync_Throws_WhenT{{arity}}_Map_ReturnsNull()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     
                     await Should.ThrowAsync<ArgumentNullException>(() => union.MapAsync(
                 {{_arities.Select(i => MapLineNullAsync(i, i == arity)).JoinCommaSeparatedLines().Indent(2)}}
                     ));
                 }   
                 """;
    }

    private static string TaskMap(int arity)
    {
        return $$"""
                 [Test]
                 public async Task TaskMap_Should_InvokeT{{arity}}Map()
                 {
                     var task = Task.FromResult(MakeT{{arity}}({{arity}}));
                     
                     var result = await task.Map(
                 {{_arities.Select(i => MapLine(i, i == arity)).JoinCommaSeparatedLines().Indent(2)}}
                     );
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 """;
    }

    private static string TaskMapAsync(int arity)
    {
        return $$"""
                 [Test]
                 public async Task TaskMapAsync_Should_InvokeT{{arity}}Map()
                 {
                     var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                     var result = await task.MapAsync(
                 {{_arities.Select(i => MapLineAsync(i, i == arity)).JoinCommaSeparatedLines().Indent(2)}}
                     );
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 """;
    }

    private static string MapLine(int arity, bool isTarget)
    {
        return isTarget
            ? $"u{arity} => u{arity}.Value + 10"
            : $"u{arity} => ShouldNotBeCalled(u{arity}.Value)";
    }

    private static string MapLineAsync(int arity, bool isTarget)
    {
        return isTarget
            ? $"u{arity} => Task.FromResult(u{arity}.Value + 10)"
            : $"u{arity} => ShouldNotBeCalledAsync(u{arity}.Value)";
    }

    private static string MapLineNull(int arity, bool isTarget)
    {
        return isTarget
            ? $"u{arity} => NullFunc(u{arity}.Value)"
            : $"u{arity} => ShouldNotBeCalled(u{arity}.Value)";
    }

    private static string MapLineNullAsync(int arity, bool isTarget)
    {
        return isTarget
            ? $"u{arity} => NullAsyncFunc(u{arity}.Value)"
            : $"u{arity} => ShouldNotBeCalledAsync(u{arity}.Value)";
    }
}