using WriterLibrary;

namespace UnionTestWriters.Writers;

/// <summary>
/// Generates tests for the MapT extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class MapPartialExtensionsTestsWriter
{
    private static int[] _arities = null!;
    private static string _union = null!;

    public static string WriteFile(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{_arities.Select(i => "U" + i).JoinCommaSeparated()}>";

        return $$"""
                 {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(MapPartialExtensionsTestsWriter).FullName!)}}

                 using Toarnbeike.Unions.Generic;
                 using Toarnbeike.Unions.Generic.Extensions;
                 using Toarnbeike.Unions.Generic.TestExtensions;
                 using Toarnbeike.Unions.Tests.TestTypes;

                 namespace Toarnbeike.Unions.Tests.Extensions.Map;

                 public class Map{{arity:D2}}PartialTests
                 {
                 {{_arities.Select(FactoryMethod).JoinLines().Indent(1)}}
                 
                 {{HelperMethods().Indent(1)}}
                 
                 {{_arities.Select(MapT).JoinParagraphs().Indent(1)}}
                 
                 {{_arities.Select(MapTAsync).JoinParagraphs().Indent(1)}}
                 
                 {{_arities.Select(TaskMapT).JoinParagraphs().Indent(1)}}
                 
                 {{_arities.Select(TaskMapTAsync).JoinParagraphs().Indent(1)}}
                 }
                 """;
    }

    private static string FactoryMethod(int arity)
    {
        return $"private static {_union} MakeT{arity}(int v) => {_union}.FromT{arity}(new U{arity}(v));";
    }

    private static string HelperMethods()
    {
        return $"""
                private static int? NullFunc(int _) => null;
                private static Task<int?> NullAsyncFunc(int _) => Task.FromResult<int?>(null);
                private static int ShouldNotBeCalled(int _) => throw new ShouldNotBeCalledException();
                private static Task<int> ShouldNotBeCalledAsync(int _) => throw new ShouldNotBeCalledException();
                """;
    }

    private static string MapT(int arity)
    {
        var otherArity = arity == 1 ? 2 : 1;

        return $$"""
                 [Test]
                 public void MapT{{arity}}_Should_Invoke_T{{arity}}_Map()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     var result = union.MapT{{arity}}(u{{arity}} => u{{arity}}.Value + 10);
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 
                 {{_arities.Where(a => a != arity).Select(a => NotInvoke(a, arity)).JoinParagraphs()}}

                 [Test]
                 public void MapT{{arity}}_Throws_When_T{{arity}}_Map_ReturnsNull()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     
                     Should.Throw<ArgumentNullException>(() => union.MapT{{arity}}(u{{arity}} => NullFunc(u{{arity}}.Value)));
                 }
                 """;
    }

    private static string NotInvoke(int otherArity, int testedArity)
    {
        return $$"""
                [Test]
                public void MapT{{testedArity}}_Should_NotInvoke_WhenT{{otherArity}}()
                {
                    var union = MakeT{{otherArity}}({{otherArity}});

                    var result = union.MapT{{testedArity}}(u{{testedArity}} => ShouldNotBeCalled(u{{testedArity}}.Value));

                    result.ShouldBeT{{otherArity}}().Value.ShouldBe({{otherArity}});
                }
                """;
    }

    private static string MapTAsync(int arity)
    {
        var otherArity = arity == 1 ? 2 : 1;

        return $$"""
                 [Test]
                 public async Task MapT{{arity}}Async_Should_Invoke_T{{arity}}_Map()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     var result = await union.MapT{{arity}}Async(u{{arity}} => Task.FromResult(u{{arity}}.Value + 10));
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 {{_arities.Where(a => a != arity).Select(a => NotInvokeAsync(a, arity)).JoinParagraphs()}}
             

                 [Test]
                 public async Task MapT{{arity}}Async_Throws_When_T{{arity}}_Map_ReturnsNull()
                 {
                     var union = MakeT{{arity}}({{arity}});
                     
                     await Should.ThrowAsync<ArgumentNullException>(() => union.MapT{{arity}}Async(u{{arity}} => NullAsyncFunc(u{{arity}}.Value)));
                 }
                 """;
    }

    private static string NotInvokeAsync(int otherArity, int testedArity)
    {
        return $$"""
                [Test]
                public async Task MapT{{testedArity}}Async_Should_NotInvoke_WhenT{{otherArity}}()
                {
                    var union = MakeT{{otherArity}}({{otherArity}});

                    var result = await union.MapT{{testedArity}}Async(u{{testedArity}} => ShouldNotBeCalledAsync(u{{testedArity}}.Value));

                    result.ShouldBeT{{otherArity}}().Value.ShouldBe({{otherArity}});
                }
                """;
    }

    private static string TaskMapT(int arity)
    {
        return $$"""
                 [Test]
                 public async Task TaskMapT{{arity}}_Should_Invoke_T{{arity}}_Map()
                 {
                     var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                     var result = await task.MapT{{arity}}(u{{arity}} => u{{arity}}.Value + 10);
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 """;
    }

    private static string TaskMapTAsync(int arity)
    {

        return $$"""
                 [Test]
                 public async Task TaskMapT{{arity}}Async_Should_Invoke_T{{arity}}_Map()
                 {
                     var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                     var result = await task.MapT{{arity}}Async(u{{arity}} => Task.FromResult(u{{arity}}.Value + 10));
                     
                     result.ShouldBeT{{arity}}().ShouldBe({{arity + 10}});
                 }
                 """;
    }
}