using WriterLibrary;

namespace UnionTestWriters.Writers;

/// <summary>
/// Generates tests for the Match extension methods.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class MatchExtensionsTestsWriter
{
    private static Context _context = null!;

    public static string WriteFile(int arity)
    {
        var arities = Enumerable.Range(1, arity).ToArray();
        _context = new Context(
            Arities: arities,
            Union: $"Union<{string.Join(',', arities.Select(i => "U" + i))}>"
        );

        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(MatchExtensionsTestsWriter).FullName!)}}
            
            using Toarnbeike.Unions.Generic;
            using Toarnbeike.Unions.Generic.Extensions;
            using Toarnbeike.Unions.Tests.TestTypes;

            namespace Toarnbeike.Unions.Tests.Extensions.Match;

            public class Match{{arity:D2}}ExtensionTests
            {
            {{arities.Select(FactoryMethod).JoinLines().Indent(1)}}
            
            {{arities.Select(MatchTest).JoinParagraphs().Indent(1)}}
            
            {{arities.Select(MatchNullTest).JoinParagraphs().Indent(1)}}
            
            {{MatchInvalidIndex().Indent(1)}}
            
            {{arities.Select(MatchAsyncTest).JoinParagraphs().Indent(1)}}
            
            {{arities.Select(MatchNullAsyncTest).JoinParagraphs().Indent(1)}}
            
            {{MatchInvalidIndexAsync().Indent(1)}}
            
            {{arities.Select(TaskMatchTest).JoinParagraphs().Indent(1)}}
            
            {{arities.Select(TaskMatchAsyncTest).JoinParagraphs().Indent(1)}}
            }
            """;
    }

    private static string FactoryMethod(int arity)
    {
        return $"private static {_context.Union} MakeT{arity}(int v) => {_context.Union}.FromT{arity}(new U{arity}(v));";
    }

    private static string MatchTest(int arity)
    {
        return $$"""
            [Test]
            public void Match_Should_Invoke_T{{arity}}_Handler()
            {
                var union = MakeT{{arity}}({{arity}});
                var result = union.Match(
            {{_context.Arities.Select(MatchLine).JoinCommaSeparatedLines().Indent(2)}}
                );

                result.ShouldBe("T{{arity}}:{{arity}}");
            }
            """;
    }

    private static string MatchAsyncTest(int arity)
    {
        return $$"""
            [Test]
            public async Task MatchAsync_Should_Invoke_T{{arity}}_Handler()
            {
                var union = MakeT{{arity}}({{arity}});
                var result = await union.MatchAsync(
            {{_context.Arities.Select(MatchAsyncLine).JoinCommaSeparatedLines().Indent(2)}}
                );

                result.ShouldBe("T{{arity}}:{{arity}}");
            }
            """;
    }

    private static string TaskMatchTest(int arity)
    {
        return $$"""
            [Test]
            public async Task TaskMatch_Should_Invoke_T{{arity}}_Handler()
            {
                var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                var result = await task.Match(
            {{_context.Arities.Select(MatchLine).JoinCommaSeparatedLines().Indent(2)}}
                );
        
                result.ShouldBe("T{{arity}}:{{arity}}");
            }
            """;
    }

    private static string TaskMatchAsyncTest(int arity)
    {
        return $$"""
            [Test]
            public async Task TaskMatchAsync_Should_Invoke_T{{arity}}_Handler()
            {
                var task = Task.FromResult(MakeT{{arity}}({{arity}}));

                var result = await task.MatchAsync(
            {{_context.Arities.Select(MatchAsyncLine).JoinCommaSeparatedLines().Indent(2)}}
                );

                result.ShouldBe("T{{arity}}:{{arity}}");
            }
            """;
    }

    private static string MatchLine(int arity)
    {
        return $$"""
            t{{arity}} => $"T{{arity}}:{t{{arity}}.Value}"
            """;
    }

    private static string MatchAsyncLine(int arity)
    {
        return $$"""
            async t{{arity}} => { await Task.Yield(); return $"T{{arity}}:{t{{arity}}.Value}"; }
            """;
    }

    private static string MatchNullTest(int arity)
    {
        return $$"""
            [Test]
            public void Match_Should_Throw_On_Null_T{{arity}}_Handler()
            {
                var union = MakeT{{arity}}({{arity}});
                Should.Throw<ArgumentNullException>(() => union.Match({{NullArguments(arity)}}));
            }
            """;
    }

    private static string MatchNullAsyncTest(int arity)
    {
        return $$"""
            [Test]
            public async Task MatchAsync_Should_Throw_On_Null_T{{arity}}_Handler()
            {
                var union = MakeT{{arity}}({{arity}});
                await Should.ThrowAsync<ArgumentNullException>(async () => await union.Match({{NullAsyncArguments(arity)}}));
            }
            """;
    }

    private static string MatchInvalidIndex()
    {
        return $$"""
            [Test]
            public void Match_Should_Throw_On_Invalid_Index()
            {
                var invalid = new {{_context.Union}}();

                var ex = Should.Throw<InvalidOperationException>(() => invalid.Match({{ValidArguments()}}));
                ex.Message.ShouldBe("Union index 0 is invalid.");
            }
            """;
    }

    private static string MatchInvalidIndexAsync()
    {
        return $$"""
            [Test]
            public async Task MatchAsync_Should_Throw_On_Invalid_Index()
            {
                var invalid = new {{_context.Union}}();

                var ex = await Should.ThrowAsync<InvalidOperationException>(async () => await invalid.MatchAsync({{ValidAsyncArguments()}}));
                ex.Message.ShouldBe("Union index 0 is invalid.");
            }
            """;
    }

    private static string NullArguments(int arity)
    {
        return _context.Arities.Select(i => i == arity ? "null!" : $"_ => {i}").JoinCommaSeparated();
    }

    private static string NullAsyncArguments(int arity)
    {
        return _context.Arities.Select(i => i == arity ? "null!" : $"_ => Task.FromResult({i})").JoinCommaSeparated();
    }

    private static string ValidArguments()
    {
        return _context.Arities.Select(i => $"_ => {i}").JoinCommaSeparated();
    }

    private static string ValidAsyncArguments()
    {
        return _context.Arities.Select(i => $"_ => Task.FromResult({i})").JoinCommaSeparated();
    }

    private sealed record Context(int[] Arities, string Union);
}

