using WriterLibrary;

namespace UnionTestWriters.Writers;

/// <summary>
/// Generates tests for the base methods available on Union{T1..Tn}.
/// This code is build-time tooling; readability and determinism are preferred over abstraction.
/// </summary>
internal static class UnionTestWriter
{
    // Generation context, set once per WriteFile call
    private static int[] _arities = null!;
    private static string _union = null!;

    public static string WriteFile(int arity)
    {
        _arities = [.. Enumerable.Range(1, arity)];
        _union = $"Union<{string.Join(',', _arities.Select(i => "U" + i))}>";

        return $$"""
            {{AutoGeneratedMessageWriter.GetAutoGeneratedMessage(typeof(UnionTestWriter).FullName!)}}

            using Toarnbeike.Unions.Generic;
            using Toarnbeike.Unions.Tests.TestTypes;
            
            namespace Toarnbeike.Unions.Tests;

            public class Union{{arity:D2}}Tests
            {
            {{_arities.Select(FromTTests).JoinParagraphs().Indent(1)}}
            
            {{_arities.Select(FromTNullTests).JoinParagraphs().Indent(1)}}
            
            {{_arities.Select(AsTTests).JoinParagraphs().Indent(1)}}
            
            {{_arities.Select(TryGetTTests).JoinParagraphs().Indent(1)}}
            
            {{DefaultInstanceTest().Indent(1)}}
            
            {{EqualityTests().Indent(1)}}
            
            {{_arities.Select(DebuggerToStringTest).JoinParagraphs().Indent(1)}}

            {{DebuggerToStringTestUninitialized().Indent(1)}}
            }
            """;
    }

    private static string FromTTests(int arity)
    {
        return $$"""
            [Test]
            public void FromT{{arity}}_SetsIndex{{arity}}()
            {
                var union = {{_union}}.FromT{{arity}}(new U{{arity}}({{arity}}));

                union.Index.ShouldBe((byte){{arity}});
                union.IsT{{arity}}.ShouldBeTrue();
            {{_arities.Where(i => i != arity).Select(i => $"union.IsT{i}.ShouldBeFalse();").JoinLines().Indent(1)}}
            }
            """;
    }

    private static string FromTNullTests(int arity)
    {
        return $$"""
            [Test]
            public void FromT{{arity}}_Throws_WhenValueIsNull()
            {
                Should.Throw<ArgumentNullException>(() => {{_union}}.FromT{{arity}}(null!));
            }
            """;
    }

    private static string AsTTests(int arity)
    {
        var wrongArity = arity == 1 ? 2 : 1;
        return $$"""
            [Test]
            public void AsT{{arity}}_ReturnsValue_WhenCorrectVariant()
            {
                var expected = new U{{arity}}({{arity}});
                var union = {{_union}}.FromT{{arity}}(expected);

                union.AsT{{arity}}.ShouldBe(expected);
            }

            [Test]
            public void AsT{{arity}}_Throws_WhenWrongVariant()
            {
                var expected = new U{{wrongArity}}({{arity}});
                var union = {{_union}}.FromT{{wrongArity}}(expected);

                var ex = Should.Throw<InvalidOperationException>(() => _ = union.AsT{{arity}});
                ex.Message.ShouldBe("Union is not in T{{arity}} state.");
            }
            """;
    }

    private static string TryGetTTests(int arity)
    {
        var wrongArity = arity == 1 ? 2 : 1;
        return $$"""
            [Test]
            public void TryGetT{{arity}}_ReturnsTrue_AndOutputsValue_WhenT{{arity}}()
            {
                var expected = new U{{arity}}({{arity}});
                var union = {{_union}}.FromT{{arity}}(expected);

                union.TryGetT{{arity}}(out var actual).ShouldBeTrue();
                actual.ShouldBe(expected);
            }

            [Test]
            public void TryGetT{{arity}}_ReturnFalse_AndOutputsDefault_WhenNotT{{arity}}()
            {
                var expected = new U{{wrongArity}}({{arity}});
                var union = {{_union}}.FromT{{wrongArity}}(expected);

                union.TryGetT{{arity}}(out var actual).ShouldBeFalse();
                actual.ShouldBe(null);
            }
            """;
    }

    private static string DefaultInstanceTest()
    {
        return $$"""
            [Test]
            public void DefaultInstance_HasIndex0_AndIsInvalid()
            {
                var union = default({{_union}});
        
                union.Index.ShouldBe((byte)0);

            {{_arities.Select(i => $"union.IsT{i}.ShouldBeFalse();").JoinLines().Indent(1)}}
              
            {{_arities.Select(i => $"union.TryGetT{i}(out _).ShouldBeFalse();").JoinLines().Indent(1)}}
        
            {{_arities.Select(i => $"Should.Throw<InvalidOperationException>(() => _ = union.AsT{i});").JoinLines().Indent(1)}}
            }
            """;
    }

    private static string EqualityTests()
    {
        return $$"""
            [Test]
            public void Equality_Works_ForSameVariant_AndSameValue()
            {
                var a = {{_union}}.FromT1(new U1(1));
                var b = {{_union}}.FromT1(new U1(1));

                a.ShouldBe(b);
            }

            [Test]
            public void Equality_Fails_ForDifferentVariants()
            {
                var a = {{_union}}.FromT1(new U1(1));
                var b = {{_union}}.FromT2(new U2(1));

                a.ShouldNotBe(b);
            }

            [Test]
            public void Equality_Fails_ForSameVariant_AndDifferentValue()
            {
                var a = {{_union}}.FromT1(new U1(1));    
                var b = {{_union}}.FromT1(new U1(2));
        
                a.ShouldNotBe(b);
            }
            """;
    }

    private static string DebuggerToStringTest(int arity)
    {
        return $$"""
            [Test]
            public void DebuggerToString_ReturnsExpectedFormat_WhenT{{arity}}()
            {
                var union = {{_union}}.FromT{{arity}}(new U{{arity}}({{arity}}));
                var type = typeof({{_union}});
                var method = type.GetMethod("DebuggerToString", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                var actual = (string)method!.Invoke(union, null)!;
                actual.ShouldBe("T{{arity}} (U{{arity}}) = U{{arity}} { Value = {{arity}} }");
            }
            """;
    }

    private static string DebuggerToStringTestUninitialized()
    {
        return $$"""
                 [Test]
                 public void DebuggerToString_ReturnsExpectedFormat_WhenUninitialized()
                 {
                     var union = default({{_union}});
                     var type = typeof({{_union}});
                     var method = type.GetMethod("DebuggerToString", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                     var actual = (string)method!.Invoke(union, null)!;
                     actual.ShouldBe("<uninitialized>");
                 }
                 """;
    }
}