# nullable enable

// <auto-generated>
//   This file was generated by a tool.
//   Writer: UnionTestWriters.Writers.TestExtensionsTestsWriter (v. 2.0.0-alpha.1)
//   Created: 2026-04-21 10:01:16Z
//   These test are auto-generated. Do not modify.
// </auto-generated>

using Toarnbeike.Unions.Generic;
using Toarnbeike.Unions.Generic.TestExtensions;
using Toarnbeike.Unions.Tests.TestTypes;

namespace Toarnbeike.Unions.Tests.TestExtensions;

public class TestExtensions07Tests
{
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT1(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT1(new U1(v));
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT2(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT2(new U2(v));
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT3(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT3(new U3(v));
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT4(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT4(new U4(v));
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT5(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT5(new U5(v));
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT6(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT6(new U6(v));
    private static Union<U1,U2,U3,U4,U5,U6,U7> MakeT7(int v) => Union<U1,U2,U3,U4,U5,U6,U7>.FromT7(new U7(v));

    [Test]
    public void ShouldBeT1_Should_ReturnT1Value_WhenUnionIsT1()
    {
        var union = MakeT1(1);
    
        var result = union.ShouldBeT1();
    
        result.Value.ShouldBe(1);
    }
    
    [Test]
    public void ShouldBeT1_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT1()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT1_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT2(2);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT1()).Message.ShouldBe("Expected union to be T1, but it was T2 (T2 (U2) = U2 { Value = 2 }).");
    }
    
    [Test]
    public void ShouldBeT2_Should_ReturnT2Value_WhenUnionIsT2()
    {
        var union = MakeT2(2);
    
        var result = union.ShouldBeT2();
    
        result.Value.ShouldBe(2);
    }
    
    [Test]
    public void ShouldBeT2_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT2()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT2_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT2()).Message.ShouldBe("Expected union to be T2, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
    
    [Test]
    public void ShouldBeT3_Should_ReturnT3Value_WhenUnionIsT3()
    {
        var union = MakeT3(3);
    
        var result = union.ShouldBeT3();
    
        result.Value.ShouldBe(3);
    }
    
    [Test]
    public void ShouldBeT3_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT3()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT3_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT3()).Message.ShouldBe("Expected union to be T3, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
    
    [Test]
    public void ShouldBeT4_Should_ReturnT4Value_WhenUnionIsT4()
    {
        var union = MakeT4(4);
    
        var result = union.ShouldBeT4();
    
        result.Value.ShouldBe(4);
    }
    
    [Test]
    public void ShouldBeT4_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT4()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT4_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT4()).Message.ShouldBe("Expected union to be T4, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
    
    [Test]
    public void ShouldBeT5_Should_ReturnT5Value_WhenUnionIsT5()
    {
        var union = MakeT5(5);
    
        var result = union.ShouldBeT5();
    
        result.Value.ShouldBe(5);
    }
    
    [Test]
    public void ShouldBeT5_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT5()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT5_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT5()).Message.ShouldBe("Expected union to be T5, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
    
    [Test]
    public void ShouldBeT6_Should_ReturnT6Value_WhenUnionIsT6()
    {
        var union = MakeT6(6);
    
        var result = union.ShouldBeT6();
    
        result.Value.ShouldBe(6);
    }
    
    [Test]
    public void ShouldBeT6_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT6()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT6_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT6()).Message.ShouldBe("Expected union to be T6, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
    
    [Test]
    public void ShouldBeT7_Should_ReturnT7Value_WhenUnionIsT7()
    {
        var union = MakeT7(7);
    
        var result = union.ShouldBeT7();
    
        result.Value.ShouldBe(7);
    }
    
    [Test]
    public void ShouldBeT7_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2,U3,U4,U5,U6,U7> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT7()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT7_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT7()).Message.ShouldBe("Expected union to be T7, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
}