# nullable enable

// <auto-generated>
//   This file was generated by a tool.
//   Writer: UnionTestWriters.Writers.TestExtensionsTestsWriter (v. 2.0.0-alpha.1)
//   Created: 2026-04-21 10:01:16Z
//   These test are auto-generated. Do not modify.
// </auto-generated>

using Toarnbeike.Unions.Generic;
using Toarnbeike.Unions.Generic.TestExtensions;
using Toarnbeike.Unions.Tests.TestTypes;

namespace Toarnbeike.Unions.Tests.TestExtensions;

public class TestExtensions02Tests
{
    private static Union<U1,U2> MakeT1(int v) => Union<U1,U2>.FromT1(new U1(v));
    private static Union<U1,U2> MakeT2(int v) => Union<U1,U2>.FromT2(new U2(v));

    [Test]
    public void ShouldBeT1_Should_ReturnT1Value_WhenUnionIsT1()
    {
        var union = MakeT1(1);
    
        var result = union.ShouldBeT1();
    
        result.Value.ShouldBe(1);
    }
    
    [Test]
    public void ShouldBeT1_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT1()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT1_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT2(2);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT1()).Message.ShouldBe("Expected union to be T1, but it was T2 (T2 (U2) = U2 { Value = 2 }).");
    }
    
    [Test]
    public void ShouldBeT2_Should_ReturnT2Value_WhenUnionIsT2()
    {
        var union = MakeT2(2);
    
        var result = union.ShouldBeT2();
    
        result.Value.ShouldBe(2);
    }
    
    [Test]
    public void ShouldBeT2_Should_Throw_WhenUnionIsUninitialized()
    {
        Union<U1,U2> union = default;
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT2()).Message.ShouldBe("Union is in the uninitialized (default) state.");
    }
    
    [Test]
    public void ShouldBeT2_Should_Throw_WhenUnionIsOtherArity()
    {
        var union = MakeT1(1);
    
        Should.Throw<AssertionFailedException>(() => union.ShouldBeT2()).Message.ShouldBe("Expected union to be T2, but it was T1 (T1 (U1) = U1 { Value = 1 }).");
    }
}